var annotated_dup =
[
    [ "num", "namespacenum.html", [
      [ "backends", "namespacenum_1_1backends.html", [
        [ "opt", "namespacenum_1_1backends_1_1opt.html", [
          [ "fft_plan_impl", "structnum_1_1backends_1_1opt_1_1fft__plan__impl.html", "structnum_1_1backends_1_1opt_1_1fft__plan__impl" ]
        ] ],
        [ "seq", "namespacenum_1_1backends_1_1seq.html", [
          [ "fft_plan_impl", "structnum_1_1backends_1_1seq_1_1fft__plan__impl.html", "structnum_1_1backends_1_1seq_1_1fft__plan__impl" ]
        ] ],
        [ "stdsimd", "namespacenum_1_1backends_1_1stdsimd.html", [
          [ "fft_plan_impl", "structnum_1_1backends_1_1stdsimd_1_1fft__plan__impl.html", "structnum_1_1backends_1_1stdsimd_1_1fft__plan__impl" ]
        ] ]
      ] ],
      [ "debug", "namespacenum_1_1debug.html", [
        [ "probe_rng", "structnum_1_1debug_1_1probe__rng.html", "structnum_1_1debug_1_1probe__rng" ],
        [ "scoped_preset", "classnum_1_1debug_1_1scoped__preset.html", "classnum_1_1debug_1_1scoped__preset" ]
      ] ],
      [ "detail", "namespacenum_1_1detail.html", [
        [ "aligned_deleter", "classnum_1_1detail_1_1aligned__deleter.html", "classnum_1_1detail_1_1aligned__deleter" ],
        [ "assembled_blocks", "structnum_1_1detail_1_1assembled__blocks.html", "structnum_1_1detail_1_1assembled__blocks" ],
        [ "block_layout", "structnum_1_1detail_1_1block__layout.html", "structnum_1_1detail_1_1block__layout" ],
        [ "CubicSigma", "structnum_1_1detail_1_1CubicSigma.html", null ],
        [ "CubicSigma< 2 >", "structnum_1_1detail_1_1CubicSigma_3_012_01_4.html", null ],
        [ "CubicSigma< 3 >", "structnum_1_1detail_1_1CubicSigma_3_013_01_4.html", null ],
        [ "entry_of", "structnum_1_1detail_1_1entry__of.html", "structnum_1_1detail_1_1entry__of" ],
        [ "entry_of< A, std::void_t< decltype(std::declval< const A & >()(std::size_t{0}, std::size_t{0}))> >", "structnum_1_1detail_1_1entry__of_3_01A_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01con57fa97d7795be26705869eb4c04ef770.html", "structnum_1_1detail_1_1entry__of_3_01A_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01con57fa97d7795be26705869eb4c04ef770" ],
        [ "scalar_of", "structnum_1_1detail_1_1scalar__of.html", "structnum_1_1detail_1_1scalar__of" ],
        [ "scalar_of< V, std::void_t< decltype(std::declval< const V & >()[std::size_t{0}])> >", "structnum_1_1detail_1_1scalar__of_3_01V_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01co5bc96d4db27590679512dbf4980100eb.html", "structnum_1_1detail_1_1scalar__of_3_01V_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01co5bc96d4db27590679512dbf4980100eb" ],
        [ "SpikyDW", "structnum_1_1detail_1_1SpikyDW.html", null ],
        [ "SpikyDW< 2 >", "structnum_1_1detail_1_1SpikyDW_3_012_01_4.html", null ],
        [ "SpikyDW< 3 >", "structnum_1_1detail_1_1SpikyDW_3_013_01_4.html", null ]
      ] ],
      [ "kernel", "namespacenum_1_1kernel.html", [
        [ "contract", "namespacenum_1_1kernel_1_1contract.html", [
          [ "alias_safe_t", "structnum_1_1kernel_1_1contract_1_1alias__safe__t.html", null ],
          [ "ordered_t", "structnum_1_1kernel_1_1contract_1_1ordered__t.html", null ],
          [ "throughput_t", "structnum_1_1kernel_1_1contract_1_1throughput__t.html", null ]
        ] ],
        [ "dot2_result", "structnum_1_1kernel_1_1dot2__result.html", "structnum_1_1kernel_1_1dot2__result" ],
        [ "dot_norm_result", "structnum_1_1kernel_1_1dot__norm__result.html", "structnum_1_1kernel_1_1dot__norm__result" ],
        [ "krylov_result", "structnum_1_1kernel_1_1krylov__result.html", "structnum_1_1kernel_1_1krylov__result" ]
      ] ],
      [ "law", "namespacenum_1_1law.html", [
        [ "additive_group", "structnum_1_1law_1_1additive__group.html", "structnum_1_1law_1_1additive__group" ],
        [ "endomorphism", "structnum_1_1law_1_1endomorphism.html", "structnum_1_1law_1_1endomorphism" ],
        [ "field", "structnum_1_1law_1_1field.html", "structnum_1_1law_1_1field" ],
        [ "hilbert_space", "structnum_1_1law_1_1hilbert__space.html", "structnum_1_1law_1_1hilbert__space" ],
        [ "inner_product_space", "structnum_1_1law_1_1inner__product__space.html", "structnum_1_1law_1_1inner__product__space" ],
        [ "linear_map", "structnum_1_1law_1_1linear__map.html", "structnum_1_1law_1_1linear__map" ],
        [ "linear_subspace", "structnum_1_1law_1_1linear__subspace.html", "structnum_1_1law_1_1linear__subspace" ],
        [ "meet", "structnum_1_1law_1_1meet.html", "structnum_1_1law_1_1meet" ],
        [ "meet< void, B >", "structnum_1_1law_1_1meet_3_01void_00_01B_01_4.html", "structnum_1_1law_1_1meet_3_01void_00_01B_01_4" ],
        [ "normal", "structnum_1_1law_1_1normal.html", "structnum_1_1law_1_1normal" ],
        [ "normed_space", "structnum_1_1law_1_1normed__space.html", "structnum_1_1law_1_1normed__space" ],
        [ "projection", "structnum_1_1law_1_1projection.html", "structnum_1_1law_1_1projection" ],
        [ "psd", "structnum_1_1law_1_1psd.html", "structnum_1_1law_1_1psd" ],
        [ "psd_on", "structnum_1_1law_1_1psd__on.html", "structnum_1_1law_1_1psd__on" ],
        [ "restricted_to", "structnum_1_1law_1_1restricted__to.html", "structnum_1_1law_1_1restricted__to" ],
        [ "restricted_to< projection, S >", "structnum_1_1law_1_1restricted__to_3_01projection_00_01S_01_4.html", "structnum_1_1law_1_1restricted__to_3_01projection_00_01S_01_4" ],
        [ "restricted_to< psd, S >", "structnum_1_1law_1_1restricted__to_3_01psd_00_01S_01_4.html", "structnum_1_1law_1_1restricted__to_3_01psd_00_01S_01_4" ],
        [ "restricted_to< self_adjoint, S >", "structnum_1_1law_1_1restricted__to_3_01self__adjoint_00_01S_01_4.html", "structnum_1_1law_1_1restricted__to_3_01self__adjoint_00_01S_01_4" ],
        [ "restricted_to< spd, S >", "structnum_1_1law_1_1restricted__to_3_01spd_00_01S_01_4.html", "structnum_1_1law_1_1restricted__to_3_01spd_00_01S_01_4" ],
        [ "ring", "structnum_1_1law_1_1ring.html", "structnum_1_1law_1_1ring" ],
        [ "root", "structnum_1_1law_1_1root.html", "structnum_1_1law_1_1root" ],
        [ "self_adjoint", "structnum_1_1law_1_1self__adjoint.html", "structnum_1_1law_1_1self__adjoint" ],
        [ "self_adjoint_on", "structnum_1_1law_1_1self__adjoint__on.html", "structnum_1_1law_1_1self__adjoint__on" ],
        [ "semiring", "structnum_1_1law_1_1semiring.html", "structnum_1_1law_1_1semiring" ],
        [ "skew_adjoint", "structnum_1_1law_1_1skew__adjoint.html", "structnum_1_1law_1_1skew__adjoint" ],
        [ "spd", "structnum_1_1law_1_1spd.html", "structnum_1_1law_1_1spd" ],
        [ "spd_on", "structnum_1_1law_1_1spd__on.html", "structnum_1_1law_1_1spd__on" ],
        [ "strongest", "structnum_1_1law_1_1strongest.html", null ],
        [ "strongest< math::type_list< L > >", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_01L_01_4_01_4.html", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_01L_01_4_01_4" ],
        [ "strongest< math::type_list< L, Rest... > >", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_01L_00_01Rest_8_8_8_01_4_01_4.html", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_01L_00_01Rest_8_8_8_01_4_01_4" ],
        [ "strongest< math::type_list<> >", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_4_01_4.html", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_4_01_4" ],
        [ "unitary", "structnum_1_1law_1_1unitary.html", "structnum_1_1law_1_1unitary" ],
        [ "vector_space", "structnum_1_1law_1_1vector__space.html", "structnum_1_1law_1_1vector__space" ]
      ] ],
      [ "linear", "namespacenum_1_1linear.html", [
        [ "props_detail", "namespacenum_1_1linear_1_1props__detail.html", [
          [ "matrix_as_operator", "structnum_1_1linear_1_1props__detail_1_1matrix__as__operator.html", "structnum_1_1linear_1_1props__detail_1_1matrix__as__operator" ],
          [ "square_tag", "structnum_1_1linear_1_1props__detail_1_1square__tag.html", "structnum_1_1linear_1_1props__detail_1_1square__tag" ]
        ] ],
        [ "band_mat_view", "classnum_1_1linear_1_1band__mat__view.html", "classnum_1_1linear_1_1band__mat__view" ],
        [ "sparse_csr_mat", "classnum_1_1linear_1_1sparse__csr__mat.html", "classnum_1_1linear_1_1sparse__csr__mat" ],
        [ "sq_mat", "classnum_1_1linear_1_1sq__mat.html", "classnum_1_1linear_1_1sq__mat" ],
        [ "structured_mat", "classnum_1_1linear_1_1structured__mat.html", "classnum_1_1linear_1_1structured__mat" ],
        [ "tri_mat", "classnum_1_1linear_1_1tri__mat.html", "classnum_1_1linear_1_1tri__mat" ]
      ] ],
      [ "markov", "namespacenum_1_1markov.html", [
        [ "metropolis_stats", "structnum_1_1markov_1_1metropolis__stats.html", "structnum_1_1markov_1_1metropolis__stats" ],
        [ "umbrella_stats", "structnum_1_1markov_1_1umbrella__stats.html", "structnum_1_1markov_1_1umbrella__stats" ],
        [ "umbrella_window", "structnum_1_1markov_1_1umbrella__window.html", "structnum_1_1markov_1_1umbrella__window" ]
      ] ],
      [ "math", "namespacenum_1_1math.html", [
        [ "detail", "namespacenum_1_1math_1_1detail.html", [
          [ "codomain_of", "structnum_1_1math_1_1detail_1_1codomain__of.html", "structnum_1_1math_1_1detail_1_1codomain__of" ],
          [ "codomain_of< basic_mat< T >, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01basic__mat_3_01T_01_4_00_01void_01_4.html", "structnum_1_1math_1_1detail_1_1codomain__of_3_01basic__mat_3_01T_01_4_00_01void_01_4" ],
          [ "codomain_of< certified_ref< T, Ps... >, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01certified__ref_3_01T_00_01Ps_8_8_8_01_4_00_01void_01_4.html", null ],
          [ "codomain_of< chebyshev_preconditioner< Op >, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01chebyshev__preconditioner_3_01Op_01_4_00_01void_01_4.html", "structnum_1_1math_1_1detail_1_1codomain__of_3_01chebyshev__preconditioner_3_01Op_01_4_00_01void_01_4" ],
          [ "codomain_of< ilu0_preconditioner, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01ilu0__preconditioner_00_01void_01_4.html", "structnum_1_1math_1_1detail_1_1codomain__of_3_01ilu0__preconditioner_00_01void_01_4" ],
          [ "codomain_of< linear::structured_mat< Mat, Ax >, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01linear_1_1structured__mat_3_01Mat_00_01Ax_01_4_00_01void_01_4.html", null ],
          [ "codomain_of< T, std::void_t< typename std::remove_cvref_t< T >::codomain_type > >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1remofaa4035848825e72bbd3c17ca9c8386a.html", "structnum_1_1math_1_1detail_1_1codomain__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1remofaa4035848825e72bbd3c17ca9c8386a" ],
          [ "declared_laws", "structnum_1_1math_1_1detail_1_1declared__laws.html", "structnum_1_1math_1_1detail_1_1declared__laws" ],
          [ "declared_laws< T, std::void_t< typename std::remove_cvref_t< T >::math_laws > >", "structnum_1_1math_1_1detail_1_1declared__laws_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1red5409402552c41b458c9f6e91803933a.html", "structnum_1_1math_1_1detail_1_1declared__laws_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1red5409402552c41b458c9f6e91803933a" ],
          [ "domain_of", "structnum_1_1math_1_1detail_1_1domain__of.html", "structnum_1_1math_1_1detail_1_1domain__of" ],
          [ "domain_of< basic_mat< T >, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01basic__mat_3_01T_01_4_00_01void_01_4.html", "structnum_1_1math_1_1detail_1_1domain__of_3_01basic__mat_3_01T_01_4_00_01void_01_4" ],
          [ "domain_of< certified_ref< T, Ps... >, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01certified__ref_3_01T_00_01Ps_8_8_8_01_4_00_01void_01_4.html", null ],
          [ "domain_of< chebyshev_preconditioner< Op >, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01chebyshev__preconditioner_3_01Op_01_4_00_01void_01_4.html", "structnum_1_1math_1_1detail_1_1domain__of_3_01chebyshev__preconditioner_3_01Op_01_4_00_01void_01_4" ],
          [ "domain_of< ilu0_preconditioner, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01ilu0__preconditioner_00_01void_01_4.html", "structnum_1_1math_1_1detail_1_1domain__of_3_01ilu0__preconditioner_00_01void_01_4" ],
          [ "domain_of< linear::structured_mat< Mat, Ax >, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01linear_1_1structured__mat_3_01Mat_00_01Ax_01_4_00_01void_01_4.html", null ],
          [ "domain_of< T, std::void_t< typename std::remove_cvref_t< T >::domain_type > >", "structnum_1_1math_1_1detail_1_1domain__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1removef0670a8658740383c2fa95fcdda309e4.html", "structnum_1_1math_1_1detail_1_1domain__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1removef0670a8658740383c2fa95fcdda309e4" ],
          [ "scalar_of", "structnum_1_1math_1_1detail_1_1scalar__of.html", "structnum_1_1math_1_1detail_1_1scalar__of" ],
          [ "scalar_of< certified_ref< T, Ps... >, void >", "structnum_1_1math_1_1detail_1_1scalar__of_3_01certified__ref_3_01T_00_01Ps_8_8_8_01_4_00_01void_01_4.html", null ],
          [ "scalar_of< T, std::void_t< typename std::remove_cvref_t< T >::value_type > >", "structnum_1_1math_1_1detail_1_1scalar__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1remove8a727e847a045837850ea248002db848.html", "structnum_1_1math_1_1detail_1_1scalar__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1remove8a727e847a045837850ea248002db848" ]
        ] ],
        [ "apply_t", "structnum_1_1math_1_1apply__t.html", "structnum_1_1math_1_1apply__t" ],
        [ "axpy_norm_sq_t", "structnum_1_1math_1_1axpy__norm__sq__t.html", "structnum_1_1math_1_1axpy__norm__sq__t" ],
        [ "axpy_t", "structnum_1_1math_1_1axpy__t.html", "structnum_1_1math_1_1axpy__t" ],
        [ "certified_ref", "classnum_1_1math_1_1certified__ref.html", "classnum_1_1math_1_1certified__ref" ],
        [ "claims_of", "structnum_1_1math_1_1claims__of.html", "structnum_1_1math_1_1claims__of" ],
        [ "claims_of< array< std::complex< T > > >", "structnum_1_1math_1_1claims__of_3_01array_3_01std_1_1complex_3_01T_01_4_01_4_01_4.html", "structnum_1_1math_1_1claims__of_3_01array_3_01std_1_1complex_3_01T_01_4_01_4_01_4" ],
        [ "claims_of< array< T > >", "structnum_1_1math_1_1claims__of_3_01array_3_01T_01_4_01_4.html", "structnum_1_1math_1_1claims__of_3_01array_3_01T_01_4_01_4" ],
        [ "claims_of< basic_mat< T > >", "structnum_1_1math_1_1claims__of_3_01basic__mat_3_01T_01_4_01_4.html", "structnum_1_1math_1_1claims__of_3_01basic__mat_3_01T_01_4_01_4" ],
        [ "claims_of< basic_vec< T > >", "structnum_1_1math_1_1claims__of_3_01basic__vec_3_01T_01_4_01_4.html", "structnum_1_1math_1_1claims__of_3_01basic__vec_3_01T_01_4_01_4" ],
        [ "claims_of< certified_ref< T, Ps... > >", "structnum_1_1math_1_1claims__of_3_01certified__ref_3_01T_00_01Ps_8_8_8_01_4_01_4.html", null ],
        [ "claims_of< linear::structured_mat< Mat, Ax > >", "structnum_1_1math_1_1claims__of_3_01linear_1_1structured__mat_3_01Mat_00_01Ax_01_4_01_4.html", "structnum_1_1math_1_1claims__of_3_01linear_1_1structured__mat_3_01Mat_00_01Ax_01_4_01_4" ],
        [ "claims_of< space::zero_sum >", "structnum_1_1math_1_1claims__of_3_01space_1_1zero__sum_01_4.html", "structnum_1_1math_1_1claims__of_3_01space_1_1zero__sum_01_4" ],
        [ "claims_of< std::complex< T > >", "structnum_1_1math_1_1claims__of_3_01std_1_1complex_3_01T_01_4_01_4.html", "structnum_1_1math_1_1claims__of_3_01std_1_1complex_3_01T_01_4_01_4" ],
        [ "claims_of< T >", "structnum_1_1math_1_1claims__of_3_01T_01_4.html", "structnum_1_1math_1_1claims__of_3_01T_01_4" ],
        [ "contains_t", "structnum_1_1math_1_1contains__t.html", "structnum_1_1math_1_1contains__t" ],
        [ "dimension_t", "structnum_1_1math_1_1dimension__t.html", "structnum_1_1math_1_1dimension__t" ],
        [ "evidence_provenance", "structnum_1_1math_1_1evidence__provenance.html", "structnum_1_1math_1_1evidence__provenance" ],
        [ "evidence_validator", "structnum_1_1math_1_1evidence__validator.html", null ],
        [ "evidence_validator< mat, law::spd >", "structnum_1_1math_1_1evidence__validator_3_01mat_00_01law_1_1spd_01_4.html", null ],
        [ "inner_t", "structnum_1_1math_1_1inner__t.html", "structnum_1_1math_1_1inner__t" ],
        [ "law_verifier", "structnum_1_1math_1_1law__verifier.html", null ],
        [ "law_verifier< law::endomorphism >", "structnum_1_1math_1_1law__verifier_3_01law_1_1endomorphism_01_4.html", null ],
        [ "law_verifier< law::linear_map >", "structnum_1_1math_1_1law__verifier_3_01law_1_1linear__map_01_4.html", null ],
        [ "law_verifier< law::normal >", "structnum_1_1math_1_1law__verifier_3_01law_1_1normal_01_4.html", null ],
        [ "law_verifier< law::projection >", "structnum_1_1math_1_1law__verifier_3_01law_1_1projection_01_4.html", null ],
        [ "law_verifier< law::psd >", "structnum_1_1math_1_1law__verifier_3_01law_1_1psd_01_4.html", null ],
        [ "law_verifier< law::psd_on< S > >", "structnum_1_1math_1_1law__verifier_3_01law_1_1psd__on_3_01S_01_4_01_4.html", null ],
        [ "law_verifier< law::self_adjoint >", "structnum_1_1math_1_1law__verifier_3_01law_1_1self__adjoint_01_4.html", null ],
        [ "law_verifier< law::self_adjoint_on< S > >", "structnum_1_1math_1_1law__verifier_3_01law_1_1self__adjoint__on_3_01S_01_4_01_4.html", null ],
        [ "law_verifier< law::skew_adjoint >", "structnum_1_1math_1_1law__verifier_3_01law_1_1skew__adjoint_01_4.html", null ],
        [ "law_verifier< law::spd >", "structnum_1_1math_1_1law__verifier_3_01law_1_1spd_01_4.html", null ],
        [ "law_verifier< law::spd_on< S > >", "structnum_1_1math_1_1law__verifier_3_01law_1_1spd__on_3_01S_01_4_01_4.html", null ],
        [ "law_verifier< law::unitary >", "structnum_1_1math_1_1law__verifier_3_01law_1_1unitary_01_4.html", null ],
        [ "linear_combination_t", "structnum_1_1math_1_1linear__combination__t.html", "structnum_1_1math_1_1linear__combination__t" ],
        [ "norm_t", "structnum_1_1math_1_1norm__t.html", "structnum_1_1math_1_1norm__t" ],
        [ "project_t", "structnum_1_1math_1_1project__t.html", "structnum_1_1math_1_1project__t" ],
        [ "scale_t", "structnum_1_1math_1_1scale__t.html", "structnum_1_1math_1_1scale__t" ],
        [ "type_list", "structnum_1_1math_1_1type__list.html", null ],
        [ "zero_like_t", "structnum_1_1math_1_1zero__like__t.html", "structnum_1_1math_1_1zero__like__t" ]
      ] ],
      [ "ode", "namespacenum_1_1ode.html", [
        [ "implicit_params", "structnum_1_1ode_1_1implicit__params.html", "structnum_1_1ode_1_1implicit__params" ]
      ] ],
      [ "operators", "namespacenum_1_1operators.html", [
        [ "backward_euler_2d", "classnum_1_1operators_1_1backward__euler__2d.html", "classnum_1_1operators_1_1backward__euler__2d" ],
        [ "callable_op", "structnum_1_1operators_1_1callable__op.html", "structnum_1_1operators_1_1callable__op" ],
        [ "dense_op", "structnum_1_1operators_1_1dense__op.html", "structnum_1_1operators_1_1dense__op" ],
        [ "laplacian_2d", "classnum_1_1operators_1_1laplacian__2d.html", "classnum_1_1operators_1_1laplacian__2d" ],
        [ "projected_op", "classnum_1_1operators_1_1projected__op.html", "classnum_1_1operators_1_1projected__op" ],
        [ "sparse_op", "structnum_1_1operators_1_1sparse__op.html", "structnum_1_1operators_1_1sparse__op" ],
        [ "structured_op", "classnum_1_1operators_1_1structured__op.html", "classnum_1_1operators_1_1structured__op" ],
        [ "sum_op", "classnum_1_1operators_1_1sum__op.html", "classnum_1_1operators_1_1sum__op" ]
      ] ],
      [ "pde", "namespacenum_1_1pde.html", [
        [ "backward_euler_operator_2d", "classnum_1_1pde_1_1backward__euler__operator__2d.html", "classnum_1_1pde_1_1backward__euler__operator__2d" ]
      ] ],
      [ "plt", "namespacenum_1_1plt.html", [
        [ "detail", "namespacenum_1_1plt_1_1detail.html", [
          [ "heatmap_entry", "structnum_1_1plt_1_1detail_1_1heatmap__entry.html", "structnum_1_1plt_1_1detail_1_1heatmap__entry" ],
          [ "plot_panel", "structnum_1_1plt_1_1detail_1_1plot__panel.html", "structnum_1_1plt_1_1detail_1_1plot__panel" ],
          [ "plot_state", "structnum_1_1plt_1_1detail_1_1plot__state.html", "structnum_1_1plt_1_1detail_1_1plot__state" ],
          [ "series_entry", "structnum_1_1plt_1_1detail_1_1series__entry.html", "structnum_1_1plt_1_1detail_1_1series__entry" ]
        ] ]
      ] ],
      [ "randommat", "namespacenum_1_1randommat.html", [
        [ "approx_chol_preconditioner", "classnum_1_1randommat_1_1approx__chol__preconditioner.html", "classnum_1_1randommat_1_1approx__chol__preconditioner" ],
        [ "cholesky_factor", "structnum_1_1randommat_1_1cholesky__factor.html", "structnum_1_1randommat_1_1cholesky__factor" ],
        [ "factor_column", "structnum_1_1randommat_1_1factor__column.html", "structnum_1_1randommat_1_1factor__column" ],
        [ "factor_entry", "structnum_1_1randommat_1_1factor__entry.html", "structnum_1_1randommat_1_1factor__entry" ]
      ] ],
      [ "scalars", "namespacenum_1_1scalars.html", [
        [ "is_complex", "structnum_1_1scalars_1_1is__complex.html", null ],
        [ "is_complex< std::complex< T > >", "structnum_1_1scalars_1_1is__complex_3_01std_1_1complex_3_01T_01_4_01_4.html", null ],
        [ "real_of", "structnum_1_1scalars_1_1real__of.html", "structnum_1_1scalars_1_1real__of" ],
        [ "real_of< std::complex< T > >", "structnum_1_1scalars_1_1real__of_3_01std_1_1complex_3_01T_01_4_01_4.html", "structnum_1_1scalars_1_1real__of_3_01std_1_1complex_3_01T_01_4_01_4" ]
      ] ],
      [ "space", "namespacenum_1_1space.html", [
        [ "zero_sum", "structnum_1_1space_1_1zero__sum.html", "structnum_1_1space_1_1zero__sum" ]
      ] ],
      [ "spectral", "namespacenum_1_1spectral.html", [
        [ "fft_plan", "classnum_1_1spectral_1_1fft__plan.html", "classnum_1_1spectral_1_1fft__plan" ],
        [ "fft_plan_impl", "structnum_1_1spectral_1_1fft__plan__impl.html", "structnum_1_1spectral_1_1fft__plan__impl" ]
      ] ],
      [ "structures", "namespacenum_1_1structures.html", [
        [ "basic_degree_queue", "classnum_1_1structures_1_1basic__degree__queue.html", "classnum_1_1structures_1_1basic__degree__queue" ],
        [ "basic_multigraph", "classnum_1_1structures_1_1basic__multigraph.html", "classnum_1_1structures_1_1basic__multigraph" ],
        [ "multi_edge", "structnum_1_1structures_1_1multi__edge.html", "structnum_1_1structures_1_1multi__edge" ]
      ] ],
      [ "auto_linear_options", "structnum_1_1auto__linear__options.html", "structnum_1_1auto__linear__options" ],
      [ "auto_linear_solver", "classnum_1_1auto__linear__solver.html", "classnum_1_1auto__linear__solver" ],
      [ "auto_resolvent_options", "structnum_1_1auto__resolvent__options.html", "structnum_1_1auto__resolvent__options" ],
      [ "auto_resolvent_solver", "classnum_1_1auto__resolvent__solver.html", "classnum_1_1auto__resolvent__solver" ],
      [ "band_mat", "classnum_1_1band__mat.html", "classnum_1_1band__mat" ],
      [ "banded_solver_result", "structnum_1_1banded__solver__result.html", "structnum_1_1banded__solver__result" ],
      [ "basic_disjoint_set", "classnum_1_1basic__disjoint__set.html", "classnum_1_1basic__disjoint__set" ],
      [ "basic_euler_steps", "classnum_1_1basic__euler__steps.html", "classnum_1_1basic__euler__steps" ],
      [ "basic_graph", "classnum_1_1basic__graph.html", "classnum_1_1basic__graph" ],
      [ "basic_histogram", "structnum_1_1basic__histogram.html", "structnum_1_1basic__histogram" ],
      [ "basic_mat", "classnum_1_1basic__mat.html", "classnum_1_1basic__mat" ],
      [ "basic_rk45_steps", "classnum_1_1basic__rk45__steps.html", "classnum_1_1basic__rk45__steps" ],
      [ "basic_rk4_2nd_steps", "classnum_1_1basic__rk4__2nd__steps.html", "classnum_1_1basic__rk4__2nd__steps" ],
      [ "basic_rk4_steps", "classnum_1_1basic__rk4__steps.html", "classnum_1_1basic__rk4__steps" ],
      [ "basic_root_result", "structnum_1_1basic__root__result.html", "structnum_1_1basic__root__result" ],
      [ "basic_running_stats", "structnum_1_1basic__running__stats.html", "structnum_1_1basic__running__stats" ],
      [ "basic_vec", "classnum_1_1basic__vec.html", "classnum_1_1basic__vec" ],
      [ "basic_verlet_steps", "classnum_1_1basic__verlet__steps.html", "classnum_1_1basic__verlet__steps" ],
      [ "basic_yoshida4_steps", "classnum_1_1basic__yoshida4__steps.html", "classnum_1_1basic__yoshida4__steps" ],
      [ "block_cholesky_factor", "structnum_1_1block__cholesky__factor.html", "structnum_1_1block__cholesky__factor" ],
      [ "block_lu_factor", "structnum_1_1block__lu__factor.html", "structnum_1_1block__lu__factor" ],
      [ "categorical_sampler", "classnum_1_1categorical__sampler.html", "classnum_1_1categorical__sampler" ],
      [ "cell_list_2d", "classnum_1_1cell__list__2d.html", "classnum_1_1cell__list__2d" ],
      [ "cell_list_3d", "classnum_1_1cell__list__3d.html", "classnum_1_1cell__list__3d" ],
      [ "cg_method", "structnum_1_1cg__method.html", "structnum_1_1cg__method" ],
      [ "cg_options", "structnum_1_1cg__options.html", "structnum_1_1cg__options" ],
      [ "chebyshev_preconditioner", "classnum_1_1chebyshev__preconditioner.html", "classnum_1_1chebyshev__preconditioner" ],
      [ "cholesky_result", "structnum_1_1cholesky__result.html", "structnum_1_1cholesky__result" ],
      [ "cluster_result", "structnum_1_1cluster__result.html", "structnum_1_1cluster__result" ],
      [ "complex_tri_diag", "structnum_1_1complex__tri__diag.html", "structnum_1_1complex__tri__diag" ],
      [ "contour_node", "structnum_1_1contour__node.html", "structnum_1_1contour__node" ],
      [ "crank_nicolson_adi", "structnum_1_1crank__nicolson__adi.html", "structnum_1_1crank__nicolson__adi" ],
      [ "dense_resolvent_solver", "classnum_1_1dense__resolvent__solver.html", "classnum_1_1dense__resolvent__solver" ],
      [ "eigen_result", "structnum_1_1eigen__result.html", "structnum_1_1eigen__result" ],
      [ "euler_method", "structnum_1_1euler__method.html", "structnum_1_1euler__method" ],
      [ "field_solver", "classnum_1_1field__solver.html", "classnum_1_1field__solver" ],
      [ "givens_rotation", "structnum_1_1givens__rotation.html", "structnum_1_1givens__rotation" ],
      [ "gmres_method", "structnum_1_1gmres__method.html", "structnum_1_1gmres__method" ],
      [ "gmres_options", "structnum_1_1gmres__options.html", "structnum_1_1gmres__options" ],
      [ "gnuplot", "classnum_1_1gnuplot.html", "classnum_1_1gnuplot" ],
      [ "grid2d", "structnum_1_1grid2d.html", "structnum_1_1grid2d" ],
      [ "grid_3d", "structnum_1_1grid__3d.html", "structnum_1_1grid__3d" ],
      [ "hessenberg_decomposition", "classnum_1_1hessenberg__decomposition.html", "classnum_1_1hessenberg__decomposition" ],
      [ "hessenberg_resolvent_solver", "classnum_1_1hessenberg__resolvent__solver.html", "classnum_1_1hessenberg__resolvent__solver" ],
      [ "ilu0_preconditioner", "classnum_1_1ilu0__preconditioner.html", "classnum_1_1ilu0__preconditioner" ],
      [ "indexed_priority_queue", "classnum_1_1indexed__priority__queue.html", "classnum_1_1indexed__priority__queue" ],
      [ "integer_range", "structnum_1_1integer__range.html", "structnum_1_1integer__range" ],
      [ "inverse_diagonal_workspace", "structnum_1_1inverse__diagonal__workspace.html", "structnum_1_1inverse__diagonal__workspace" ],
      [ "jacobi_preconditioner", "classnum_1_1jacobi__preconditioner.html", "classnum_1_1jacobi__preconditioner" ],
      [ "klu_factorization", "classnum_1_1klu__factorization.html", "classnum_1_1klu__factorization" ],
      [ "lanczos_result", "structnum_1_1lanczos__result.html", "structnum_1_1lanczos__result" ],
      [ "linear_cache", "structnum_1_1linear__cache.html", "structnum_1_1linear__cache" ],
      [ "linear_problem", "structnum_1_1linear__problem.html", "structnum_1_1linear__problem" ],
      [ "linear_solution", "structnum_1_1linear__solution.html", "structnum_1_1linear__solution" ],
      [ "lu_result", "structnum_1_1lu__result.html", "structnum_1_1lu__result" ],
      [ "magnetic_solver", "classnum_1_1magnetic__solver.html", null ],
      [ "mcmc_model", "structnum_1_1mcmc__model.html", "structnum_1_1mcmc__model" ],
      [ "metropolis_method", "structnum_1_1metropolis__method.html", "structnum_1_1metropolis__method" ],
      [ "minres_method", "structnum_1_1minres__method.html", "structnum_1_1minres__method" ],
      [ "minres_options", "structnum_1_1minres__options.html", "structnum_1_1minres__options" ],
      [ "multi_index", "structnum_1_1multi__index.html", "structnum_1_1multi__index" ],
      [ "no_pivot_lu", "structnum_1_1no__pivot__lu.html", "structnum_1_1no__pivot__lu" ],
      [ "ode_params", "structnum_1_1ode__params.html", "structnum_1_1ode__params" ],
      [ "ode_problem", "structnum_1_1ode__problem.html", "structnum_1_1ode__problem" ],
      [ "ode_result", "structnum_1_1ode__result.html", "structnum_1_1ode__result" ],
      [ "ode_step", "structnum_1_1ode__step.html", "structnum_1_1ode__step" ],
      [ "pbc_lattice_2d", "structnum_1_1pbc__lattice__2d.html", "structnum_1_1pbc__lattice__2d" ],
      [ "pcg_method", "structnum_1_1pcg__method.html", "structnum_1_1pcg__method" ],
      [ "pcg_on_method", "structnum_1_1pcg__on__method.html", "structnum_1_1pcg__on__method" ],
      [ "pcg_options", "structnum_1_1pcg__options.html", "structnum_1_1pcg__options" ],
      [ "power_result", "structnum_1_1power__result.html", "structnum_1_1power__result" ],
      [ "qr_result", "structnum_1_1qr__result.html", "structnum_1_1qr__result" ],
      [ "resolvent_factor", "classnum_1_1resolvent__factor.html", "classnum_1_1resolvent__factor" ],
      [ "rk45_method", "structnum_1_1rk45__method.html", "structnum_1_1rk45__method" ],
      [ "rk4_method", "structnum_1_1rk4__method.html", "structnum_1_1rk4__method" ],
      [ "rng_state", "structnum_1_1rng__state.html", "structnum_1_1rng__state" ],
      [ "scalar_field_2d", "classnum_1_1scalar__field__2d.html", "classnum_1_1scalar__field__2d" ],
      [ "scalar_field_3d", "classnum_1_1scalar__field__3d.html", "classnum_1_1scalar__field__3d" ],
      [ "series", "structnum_1_1series.html", "structnum_1_1series" ],
      [ "small_matrix", "structnum_1_1small__matrix.html", "structnum_1_1small__matrix" ],
      [ "small_vec", "structnum_1_1small__vec.html", "structnum_1_1small__vec" ],
      [ "solver_result", "structnum_1_1solver__result.html", "structnum_1_1solver__result" ],
      [ "sparse_resolvent_options", "structnum_1_1sparse__resolvent__options.html", "structnum_1_1sparse__resolvent__options" ],
      [ "sparse_resolvent_solver", "classnum_1_1sparse__resolvent__solver.html", "classnum_1_1sparse__resolvent__solver" ],
      [ "sph_kernel", "structnum_1_1sph__kernel.html", null ],
      [ "spmat", "classnum_1_1spmat.html", "classnum_1_1spmat" ],
      [ "step_end", "structnum_1_1step__end.html", null ],
      [ "svd_result", "structnum_1_1svd__result.html", "structnum_1_1svd__result" ],
      [ "symplectic_result", "structnum_1_1symplectic__result.html", "structnum_1_1symplectic__result" ],
      [ "symplectic_step", "structnum_1_1symplectic__step.html", "structnum_1_1symplectic__step" ],
      [ "talbot_quadrature", "structnum_1_1talbot__quadrature.html", "structnum_1_1talbot__quadrature" ],
      [ "umfpack_factor", "classnum_1_1umfpack__factor.html", "classnum_1_1umfpack__factor" ],
      [ "vec2_view", "structnum_1_1vec2__view.html", "structnum_1_1vec2__view" ],
      [ "vector_field_3d", "structnum_1_1vector__field__3d.html", "structnum_1_1vector__field__3d" ],
      [ "verlet_list_2d", "classnum_1_1verlet__list__2d.html", "classnum_1_1verlet__list__2d" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< num::multi_index >", "structstd_1_1hash_3_01num_1_1multi__index_01_4.html", "structstd_1_1hash_3_01num_1_1multi__index_01_4" ]
    ] ]
];