var hierarchy =
[
    [ "num::kernel::contract::alias_safe_t", "structnum_1_1kernel_1_1contract_1_1alias__safe__t.html", null ],
    [ "num::detail::aligned_deleter< T >", "classnum_1_1detail_1_1aligned__deleter.html", null ],
    [ "num::math::apply_t", "structnum_1_1math_1_1apply__t.html", null ],
    [ "num::randommat::approx_chol_preconditioner", "classnum_1_1randommat_1_1approx__chol__preconditioner.html", null ],
    [ "array", null, [
      [ "num::series", "structnum_1_1series.html", null ]
    ] ],
    [ "num::detail::assembled_blocks", "structnum_1_1detail_1_1assembled__blocks.html", null ],
    [ "num::auto_linear_options", "structnum_1_1auto__linear__options.html", null ],
    [ "num::auto_linear_solver", "classnum_1_1auto__linear__solver.html", null ],
    [ "num::auto_resolvent_options", "structnum_1_1auto__resolvent__options.html", null ],
    [ "num::auto_resolvent_solver", "classnum_1_1auto__resolvent__solver.html", null ],
    [ "num::math::axpy_norm_sq_t", "structnum_1_1math_1_1axpy__norm__sq__t.html", null ],
    [ "num::math::axpy_t", "structnum_1_1math_1_1axpy__t.html", null ],
    [ "num::operators::backward_euler_2d", "classnum_1_1operators_1_1backward__euler__2d.html", null ],
    [ "num::pde::backward_euler_operator_2d", "classnum_1_1pde_1_1backward__euler__operator__2d.html", null ],
    [ "num::band_mat", "classnum_1_1band__mat.html", null ],
    [ "num::linear::band_mat_view< Mat >", "classnum_1_1linear_1_1band__mat__view.html", null ],
    [ "num::banded_solver_result", "structnum_1_1banded__solver__result.html", null ],
    [ "num::structures::basic_degree_queue< Index >", "classnum_1_1structures_1_1basic__degree__queue.html", null ],
    [ "num::basic_disjoint_set< Index >", "classnum_1_1basic__disjoint__set.html", null ],
    [ "num::basic_euler_steps< RHS, State >", "classnum_1_1basic__euler__steps.html", null ],
    [ "num::basic_graph< Weight, Index >", "classnum_1_1basic__graph.html", null ],
    [ "num::basic_histogram< Float, Index >", "structnum_1_1basic__histogram.html", null ],
    [ "num::basic_mat< T >", "classnum_1_1basic__mat.html", null ],
    [ "num::basic_mat< real >", "classnum_1_1basic__mat.html", null ],
    [ "num::structures::basic_multigraph< Weight, Index >", "classnum_1_1structures_1_1basic__multigraph.html", null ],
    [ "num::basic_rk45_steps< RHS, State >", "classnum_1_1basic__rk45__steps.html", null ],
    [ "num::basic_rk4_2nd_steps< Accel, State >", "classnum_1_1basic__rk4__2nd__steps.html", null ],
    [ "num::basic_rk4_steps< RHS, State >", "classnum_1_1basic__rk4__steps.html", null ],
    [ "num::basic_root_result< Float >", "structnum_1_1basic__root__result.html", null ],
    [ "num::basic_running_stats< Float, Index >", "structnum_1_1basic__running__stats.html", null ],
    [ "num::basic_vec< T >", "classnum_1_1basic__vec.html", null ],
    [ "num::basic_vec< real >", "classnum_1_1basic__vec.html", null ],
    [ "num::basic_verlet_steps< Accel, State >", "classnum_1_1basic__verlet__steps.html", null ],
    [ "num::basic_yoshida4_steps< Accel, State >", "classnum_1_1basic__yoshida4__steps.html", null ],
    [ "num::block_cholesky_factor", "structnum_1_1block__cholesky__factor.html", null ],
    [ "num::detail::block_layout", "structnum_1_1detail_1_1block__layout.html", null ],
    [ "num::block_lu_factor", "structnum_1_1block__lu__factor.html", null ],
    [ "num::operators::callable_op< F >", "structnum_1_1operators_1_1callable__op.html", null ],
    [ "num::categorical_sampler", "classnum_1_1categorical__sampler.html", null ],
    [ "num::cell_list_2d< scalar >", "classnum_1_1cell__list__2d.html", null ],
    [ "num::cell_list_3d< scalar >", "classnum_1_1cell__list__3d.html", null ],
    [ "num::math::certified_ref< T, Properties >", "classnum_1_1math_1_1certified__ref.html", null ],
    [ "num::cg_method", "structnum_1_1cg__method.html", null ],
    [ "num::cg_options", "structnum_1_1cg__options.html", null ],
    [ "num::chebyshev_preconditioner< Op >", "classnum_1_1chebyshev__preconditioner.html", null ],
    [ "num::randommat::cholesky_factor< Float, Index >", "structnum_1_1randommat_1_1cholesky__factor.html", null ],
    [ "num::randommat::cholesky_factor< real, idx >", "structnum_1_1randommat_1_1cholesky__factor.html", null ],
    [ "num::cholesky_result", "structnum_1_1cholesky__result.html", null ],
    [ "num::math::claims_of< T >", "structnum_1_1math_1_1claims__of.html", null ],
    [ "num::math::claims_of< array< std::complex< T > > >", "structnum_1_1math_1_1claims__of_3_01array_3_01std_1_1complex_3_01T_01_4_01_4_01_4.html", null ],
    [ "num::math::claims_of< array< T > >", "structnum_1_1math_1_1claims__of_3_01array_3_01T_01_4_01_4.html", null ],
    [ "num::math::claims_of< basic_mat< T > >", "structnum_1_1math_1_1claims__of_3_01basic__mat_3_01T_01_4_01_4.html", null ],
    [ "num::math::claims_of< basic_vec< T > >", "structnum_1_1math_1_1claims__of_3_01basic__vec_3_01T_01_4_01_4.html", null ],
    [ "num::math::claims_of< linear::structured_mat< Mat, Ax > >", "structnum_1_1math_1_1claims__of_3_01linear_1_1structured__mat_3_01Mat_00_01Ax_01_4_01_4.html", null ],
    [ "num::math::claims_of< space::zero_sum >", "structnum_1_1math_1_1claims__of_3_01space_1_1zero__sum_01_4.html", null ],
    [ "num::math::claims_of< std::complex< T > >", "structnum_1_1math_1_1claims__of_3_01std_1_1complex_3_01T_01_4_01_4.html", null ],
    [ "num::math::claims_of< T >", "structnum_1_1math_1_1claims__of_3_01T_01_4.html", [
      [ "num::math::claims_of< certified_ref< T, Ps... > >", "structnum_1_1math_1_1claims__of_3_01certified__ref_3_01T_00_01Ps_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "num::cluster_result", "structnum_1_1cluster__result.html", null ],
    [ "num::math::detail::codomain_of< T, class >", "structnum_1_1math_1_1detail_1_1codomain__of.html", [
      [ "num::math::detail::codomain_of< certified_ref< T, Ps... >, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01certified__ref_3_01T_00_01Ps_8_8_8_01_4_00_01void_01_4.html", null ]
    ] ],
    [ "num::math::detail::codomain_of< basic_mat< T >, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01basic__mat_3_01T_01_4_00_01void_01_4.html", null ],
    [ "num::math::detail::codomain_of< chebyshev_preconditioner< Op >, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01chebyshev__preconditioner_3_01Op_01_4_00_01void_01_4.html", null ],
    [ "num::math::detail::codomain_of< ilu0_preconditioner, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01ilu0__preconditioner_00_01void_01_4.html", null ],
    [ "num::math::detail::codomain_of< Mat >", "structnum_1_1math_1_1detail_1_1codomain__of.html", [
      [ "num::math::detail::codomain_of< linear::structured_mat< Mat, Ax >, void >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01linear_1_1structured__mat_3_01Mat_00_01Ax_01_4_00_01void_01_4.html", null ]
    ] ],
    [ "num::math::detail::codomain_of< T, std::void_t< typename std::remove_cvref_t< T >::codomain_type > >", "structnum_1_1math_1_1detail_1_1codomain__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1remofaa4035848825e72bbd3c17ca9c8386a.html", null ],
    [ "num::complex_tri_diag", "structnum_1_1complex__tri__diag.html", null ],
    [ "num::math::contains_t", "structnum_1_1math_1_1contains__t.html", null ],
    [ "num::contour_node", "structnum_1_1contour__node.html", null ],
    [ "num::crank_nicolson_adi", "structnum_1_1crank__nicolson__adi.html", null ],
    [ "num::detail::CubicSigma< Dim >", "structnum_1_1detail_1_1CubicSigma.html", null ],
    [ "num::detail::CubicSigma< 2 >", "structnum_1_1detail_1_1CubicSigma_3_012_01_4.html", null ],
    [ "num::detail::CubicSigma< 3 >", "structnum_1_1detail_1_1CubicSigma_3_013_01_4.html", null ],
    [ "num::math::detail::declared_laws< T, class >", "structnum_1_1math_1_1detail_1_1declared__laws.html", null ],
    [ "num::math::detail::declared_laws< T, std::void_t< typename std::remove_cvref_t< T >::math_laws > >", "structnum_1_1math_1_1detail_1_1declared__laws_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1red5409402552c41b458c9f6e91803933a.html", null ],
    [ "num::operators::dense_op", "structnum_1_1operators_1_1dense__op.html", null ],
    [ "num::dense_resolvent_solver", "classnum_1_1dense__resolvent__solver.html", null ],
    [ "num::math::dimension_t", "structnum_1_1math_1_1dimension__t.html", null ],
    [ "num::field_solver::dirichlet_bc", "structnum_1_1field__solver_1_1dirichlet__bc.html", null ],
    [ "num::math::detail::domain_of< T, class >", "structnum_1_1math_1_1detail_1_1domain__of.html", [
      [ "num::math::detail::domain_of< certified_ref< T, Ps... >, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01certified__ref_3_01T_00_01Ps_8_8_8_01_4_00_01void_01_4.html", null ]
    ] ],
    [ "num::math::detail::domain_of< basic_mat< T >, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01basic__mat_3_01T_01_4_00_01void_01_4.html", null ],
    [ "num::math::detail::domain_of< chebyshev_preconditioner< Op >, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01chebyshev__preconditioner_3_01Op_01_4_00_01void_01_4.html", null ],
    [ "num::math::detail::domain_of< ilu0_preconditioner, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01ilu0__preconditioner_00_01void_01_4.html", null ],
    [ "num::math::detail::domain_of< Mat >", "structnum_1_1math_1_1detail_1_1domain__of.html", [
      [ "num::math::detail::domain_of< linear::structured_mat< Mat, Ax >, void >", "structnum_1_1math_1_1detail_1_1domain__of_3_01linear_1_1structured__mat_3_01Mat_00_01Ax_01_4_00_01void_01_4.html", null ]
    ] ],
    [ "num::math::detail::domain_of< T, std::void_t< typename std::remove_cvref_t< T >::domain_type > >", "structnum_1_1math_1_1detail_1_1domain__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1removef0670a8658740383c2fa95fcdda309e4.html", null ],
    [ "num::kernel::dot2_result< T >", "structnum_1_1kernel_1_1dot2__result.html", null ],
    [ "num::kernel::dot_norm_result< T >", "structnum_1_1kernel_1_1dot__norm__result.html", null ],
    [ "num::eigen_result", "structnum_1_1eigen__result.html", null ],
    [ "num::detail::entry_of< A, class >", "structnum_1_1detail_1_1entry__of.html", null ],
    [ "num::detail::entry_of< A, std::void_t< decltype(std::declval< const A & >()(std::size_t{0}, std::size_t{0}))> >", "structnum_1_1detail_1_1entry__of_3_01A_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01con57fa97d7795be26705869eb4c04ef770.html", null ],
    [ "num::euler_method", "structnum_1_1euler__method.html", null ],
    [ "num::math::evidence_provenance", "structnum_1_1math_1_1evidence__provenance.html", null ],
    [ "num::math::evidence_validator< T, P >", "structnum_1_1math_1_1evidence__validator.html", null ],
    [ "num::math::evidence_validator< mat, law::spd >", "structnum_1_1math_1_1evidence__validator_3_01mat_00_01law_1_1spd_01_4.html", null ],
    [ "num::randommat::factor_column< Float, Index >", "structnum_1_1randommat_1_1factor__column.html", null ],
    [ "num::randommat::factor_entry< Float, Index >", "structnum_1_1randommat_1_1factor__entry.html", null ],
    [ "std::false_type", null, [
      [ "num::scalars::is_complex< T >", "structnum_1_1scalars_1_1is__complex.html", null ]
    ] ],
    [ "num::spectral::fft_plan", "classnum_1_1spectral_1_1fft__plan.html", null ],
    [ "num::spectral::fft_plan_impl", "structnum_1_1spectral_1_1fft__plan__impl.html", [
      [ "num::backends::opt::fft_plan_impl", "structnum_1_1backends_1_1opt_1_1fft__plan__impl.html", null ],
      [ "num::backends::seq::fft_plan_impl", "structnum_1_1backends_1_1seq_1_1fft__plan__impl.html", null ],
      [ "num::backends::stdsimd::fft_plan_impl", "structnum_1_1backends_1_1stdsimd_1_1fft__plan__impl.html", null ]
    ] ],
    [ "num::field_solver", "classnum_1_1field__solver.html", null ],
    [ "num::givens_rotation", "structnum_1_1givens__rotation.html", null ],
    [ "num::gmres_method", "structnum_1_1gmres__method.html", null ],
    [ "num::gmres_options", "structnum_1_1gmres__options.html", null ],
    [ "num::gnuplot", "classnum_1_1gnuplot.html", null ],
    [ "num::basic_graph< Weight, Index >::graph_edge", "structnum_1_1basic__graph_1_1graph__edge.html", null ],
    [ "num::grid2d", "structnum_1_1grid2d.html", null ],
    [ "num::grid_3d", "structnum_1_1grid__3d.html", null ],
    [ "std::hash< num::multi_index >", "structstd_1_1hash_3_01num_1_1multi__index_01_4.html", null ],
    [ "num::plt::detail::heatmap_entry", "structnum_1_1plt_1_1detail_1_1heatmap__entry.html", null ],
    [ "num::hessenberg_decomposition", "classnum_1_1hessenberg__decomposition.html", null ],
    [ "num::hessenberg_resolvent_solver", "classnum_1_1hessenberg__resolvent__solver.html", null ],
    [ "num::ilu0_preconditioner", "classnum_1_1ilu0__preconditioner.html", null ],
    [ "num::auto_linear_solver::Impl", "structnum_1_1auto__linear__solver_1_1Impl.html", null ],
    [ "num::auto_resolvent_solver::Impl", "structnum_1_1auto__resolvent__solver_1_1Impl.html", null ],
    [ "num::dense_resolvent_solver::Impl", "structnum_1_1dense__resolvent__solver_1_1Impl.html", null ],
    [ "num::klu_factorization::Impl", "structnum_1_1klu__factorization_1_1Impl.html", null ],
    [ "num::sparse_resolvent_solver::Impl", "structnum_1_1sparse__resolvent__solver_1_1Impl.html", null ],
    [ "num::umfpack_factor::Impl", "structnum_1_1umfpack__factor_1_1Impl.html", null ],
    [ "num::ode::implicit_params", "structnum_1_1ode_1_1implicit__params.html", null ],
    [ "num::indexed_priority_queue< Key, Index, Compare >", "classnum_1_1indexed__priority__queue.html", null ],
    [ "num::math::inner_t", "structnum_1_1math_1_1inner__t.html", null ],
    [ "num::integer_range", "structnum_1_1integer__range.html", null ],
    [ "num::inverse_diagonal_workspace", "structnum_1_1inverse__diagonal__workspace.html", null ],
    [ "num::basic_euler_steps< RHS, State >::iterator", "structnum_1_1basic__euler__steps_1_1iterator.html", null ],
    [ "num::basic_rk45_steps< RHS, State >::iterator", "structnum_1_1basic__rk45__steps_1_1iterator.html", null ],
    [ "num::basic_rk4_2nd_steps< Accel, State >::iterator", "structnum_1_1basic__rk4__2nd__steps_1_1iterator.html", null ],
    [ "num::basic_rk4_steps< RHS, State >::iterator", "structnum_1_1basic__rk4__steps_1_1iterator.html", null ],
    [ "num::basic_verlet_steps< Accel, State >::iterator", "structnum_1_1basic__verlet__steps_1_1iterator.html", null ],
    [ "num::basic_yoshida4_steps< Accel, State >::iterator", "structnum_1_1basic__yoshida4__steps_1_1iterator.html", null ],
    [ "num::jacobi_preconditioner", "classnum_1_1jacobi__preconditioner.html", null ],
    [ "num::klu_factorization", "classnum_1_1klu__factorization.html", null ],
    [ "num::kernel::krylov_result< T >", "structnum_1_1kernel_1_1krylov__result.html", null ],
    [ "num::lanczos_result", "structnum_1_1lanczos__result.html", null ],
    [ "num::operators::laplacian_2d", "classnum_1_1operators_1_1laplacian__2d.html", null ],
    [ "num::math::law_verifier< Law >", "structnum_1_1math_1_1law__verifier.html", null ],
    [ "num::math::law_verifier< law::endomorphism >", "structnum_1_1math_1_1law__verifier_3_01law_1_1endomorphism_01_4.html", null ],
    [ "num::math::law_verifier< law::linear_map >", "structnum_1_1math_1_1law__verifier_3_01law_1_1linear__map_01_4.html", null ],
    [ "num::math::law_verifier< law::normal >", "structnum_1_1math_1_1law__verifier_3_01law_1_1normal_01_4.html", null ],
    [ "num::math::law_verifier< law::projection >", "structnum_1_1math_1_1law__verifier_3_01law_1_1projection_01_4.html", null ],
    [ "num::math::law_verifier< law::psd >", "structnum_1_1math_1_1law__verifier_3_01law_1_1psd_01_4.html", null ],
    [ "num::math::law_verifier< law::psd_on< S > >", "structnum_1_1math_1_1law__verifier_3_01law_1_1psd__on_3_01S_01_4_01_4.html", null ],
    [ "num::math::law_verifier< law::self_adjoint >", "structnum_1_1math_1_1law__verifier_3_01law_1_1self__adjoint_01_4.html", null ],
    [ "num::math::law_verifier< law::self_adjoint_on< S > >", "structnum_1_1math_1_1law__verifier_3_01law_1_1self__adjoint__on_3_01S_01_4_01_4.html", null ],
    [ "num::math::law_verifier< law::skew_adjoint >", "structnum_1_1math_1_1law__verifier_3_01law_1_1skew__adjoint_01_4.html", null ],
    [ "num::math::law_verifier< law::spd >", "structnum_1_1math_1_1law__verifier_3_01law_1_1spd_01_4.html", null ],
    [ "num::math::law_verifier< law::spd_on< S > >", "structnum_1_1math_1_1law__verifier_3_01law_1_1spd__on_3_01S_01_4_01_4.html", null ],
    [ "num::math::law_verifier< law::unitary >", "structnum_1_1math_1_1law__verifier_3_01law_1_1unitary_01_4.html", null ],
    [ "num::linear_cache< Op, Alg >", "structnum_1_1linear__cache.html", null ],
    [ "num::math::linear_combination_t", "structnum_1_1math_1_1linear__combination__t.html", null ],
    [ "num::linear_problem< Op >", "structnum_1_1linear__problem.html", null ],
    [ "num::linear_solution", "structnum_1_1linear__solution.html", null ],
    [ "num::lu_result", "structnum_1_1lu__result.html", null ],
    [ "num::magnetic_solver", "classnum_1_1magnetic__solver.html", null ],
    [ "num::linear::props_detail::matrix_as_operator< Mat >", "structnum_1_1linear_1_1props__detail_1_1matrix__as__operator.html", null ],
    [ "num::mcmc_model", "structnum_1_1mcmc__model.html", null ],
    [ "num::law::meet< A, B >", "structnum_1_1law_1_1meet.html", null ],
    [ "num::law::meet< void, B >", "structnum_1_1law_1_1meet_3_01void_00_01B_01_4.html", null ],
    [ "num::metropolis_method", "structnum_1_1metropolis__method.html", null ],
    [ "num::markov::metropolis_stats", "structnum_1_1markov_1_1metropolis__stats.html", null ],
    [ "num::minres_method", "structnum_1_1minres__method.html", null ],
    [ "num::minres_options", "structnum_1_1minres__options.html", null ],
    [ "num::structures::multi_edge< Weight, Index >", "structnum_1_1structures_1_1multi__edge.html", null ],
    [ "num::multi_index", "structnum_1_1multi__index.html", null ],
    [ "num::no_pivot_lu", "structnum_1_1no__pivot__lu.html", null ],
    [ "num::math::norm_t", "structnum_1_1math_1_1norm__t.html", null ],
    [ "num::ode_params", "structnum_1_1ode__params.html", null ],
    [ "num::ode_problem", "structnum_1_1ode__problem.html", null ],
    [ "num::ode_result", "structnum_1_1ode__result.html", null ],
    [ "num::ode_step", "structnum_1_1ode__step.html", null ],
    [ "num::kernel::contract::ordered_t", "structnum_1_1kernel_1_1contract_1_1ordered__t.html", null ],
    [ "num::pbc_lattice_2d", "structnum_1_1pbc__lattice__2d.html", null ],
    [ "num::pcg_method< M >", "structnum_1_1pcg__method.html", null ],
    [ "num::pcg_on_method< M, Subspace >", "structnum_1_1pcg__on__method.html", null ],
    [ "num::pcg_options", "structnum_1_1pcg__options.html", null ],
    [ "num::plt::detail::plot_panel", "structnum_1_1plt_1_1detail_1_1plot__panel.html", null ],
    [ "num::plt::detail::plot_state", "structnum_1_1plt_1_1detail_1_1plot__state.html", null ],
    [ "num::power_result", "structnum_1_1power__result.html", null ],
    [ "num::debug::probe_rng", "structnum_1_1debug_1_1probe__rng.html", null ],
    [ "num::math::project_t", "structnum_1_1math_1_1project__t.html", null ],
    [ "num::operators::projected_op< Op, Subspace >", "classnum_1_1operators_1_1projected__op.html", null ],
    [ "num::qr_result", "structnum_1_1qr__result.html", null ],
    [ "num::scalars::real_of< T >", "structnum_1_1scalars_1_1real__of.html", null ],
    [ "num::scalars::real_of< std::complex< T > >", "structnum_1_1scalars_1_1real__of_3_01std_1_1complex_3_01T_01_4_01_4.html", null ],
    [ "num::resolvent_factor", "classnum_1_1resolvent__factor.html", null ],
    [ "num::law::restricted_to< L, Subspace >", "structnum_1_1law_1_1restricted__to.html", null ],
    [ "num::law::restricted_to< projection, S >", "structnum_1_1law_1_1restricted__to_3_01projection_00_01S_01_4.html", null ],
    [ "num::law::restricted_to< psd, S >", "structnum_1_1law_1_1restricted__to_3_01psd_00_01S_01_4.html", null ],
    [ "num::law::restricted_to< self_adjoint, S >", "structnum_1_1law_1_1restricted__to_3_01self__adjoint_00_01S_01_4.html", null ],
    [ "num::law::restricted_to< spd, S >", "structnum_1_1law_1_1restricted__to_3_01spd_00_01S_01_4.html", null ],
    [ "num::rk45_method", "structnum_1_1rk45__method.html", null ],
    [ "num::rk4_method", "structnum_1_1rk4__method.html", null ],
    [ "num::rng_state", "structnum_1_1rng__state.html", null ],
    [ "num::law::root", "structnum_1_1law_1_1root.html", [
      [ "num::law::additive_group", "structnum_1_1law_1_1additive__group.html", [
        [ "num::law::vector_space", "structnum_1_1law_1_1vector__space.html", [
          [ "num::law::normed_space", "structnum_1_1law_1_1normed__space.html", [
            [ "num::law::inner_product_space", "structnum_1_1law_1_1inner__product__space.html", [
              [ "num::law::hilbert_space", "structnum_1_1law_1_1hilbert__space.html", null ]
            ] ]
          ] ]
        ] ]
      ] ],
      [ "num::law::linear_map", "structnum_1_1law_1_1linear__map.html", [
        [ "num::law::endomorphism", "structnum_1_1law_1_1endomorphism.html", [
          [ "num::law::normal", "structnum_1_1law_1_1normal.html", [
            [ "num::law::self_adjoint", "structnum_1_1law_1_1self__adjoint.html", [
              [ "num::law::psd", "structnum_1_1law_1_1psd.html", [
                [ "num::law::projection", "structnum_1_1law_1_1projection.html", null ],
                [ "num::law::spd", "structnum_1_1law_1_1spd.html", null ]
              ] ]
            ] ],
            [ "num::law::skew_adjoint", "structnum_1_1law_1_1skew__adjoint.html", null ],
            [ "num::law::unitary", "structnum_1_1law_1_1unitary.html", null ]
          ] ],
          [ "num::law::self_adjoint_on< Subspace >", "structnum_1_1law_1_1self__adjoint__on.html", [
            [ "num::law::psd_on< Subspace >", "structnum_1_1law_1_1psd__on.html", [
              [ "num::law::spd_on< Subspace >", "structnum_1_1law_1_1spd__on.html", null ]
            ] ]
          ] ]
        ] ]
      ] ],
      [ "num::law::linear_subspace", "structnum_1_1law_1_1linear__subspace.html", null ],
      [ "num::law::semiring", "structnum_1_1law_1_1semiring.html", [
        [ "num::law::ring", "structnum_1_1law_1_1ring.html", [
          [ "num::law::field", "structnum_1_1law_1_1field.html", null ]
        ] ]
      ] ]
    ] ],
    [ "num::scalar_field_2d", "classnum_1_1scalar__field__2d.html", null ],
    [ "num::scalar_field_3d", "classnum_1_1scalar__field__3d.html", null ],
    [ "num::detail::scalar_of< V, class >", "structnum_1_1detail_1_1scalar__of.html", null ],
    [ "num::math::detail::scalar_of< T, class >", "structnum_1_1math_1_1detail_1_1scalar__of.html", [
      [ "num::math::detail::scalar_of< certified_ref< T, Ps... >, void >", "structnum_1_1math_1_1detail_1_1scalar__of_3_01certified__ref_3_01T_00_01Ps_8_8_8_01_4_00_01void_01_4.html", null ]
    ] ],
    [ "num::math::detail::scalar_of< T, std::void_t< typename std::remove_cvref_t< T >::value_type > >", "structnum_1_1math_1_1detail_1_1scalar__of_3_01T_00_01std_1_1void__t_3_01typename_01std_1_1remove8a727e847a045837850ea248002db848.html", null ],
    [ "num::detail::scalar_of< V, std::void_t< decltype(std::declval< const V & >()[std::size_t{0}])> >", "structnum_1_1detail_1_1scalar__of_3_01V_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01co5bc96d4db27590679512dbf4980100eb.html", null ],
    [ "num::math::scale_t", "structnum_1_1math_1_1scale__t.html", null ],
    [ "num::debug::scoped_preset", "classnum_1_1debug_1_1scoped__preset.html", null ],
    [ "num::plt::detail::series_entry", "structnum_1_1plt_1_1detail_1_1series__entry.html", null ],
    [ "num::small_matrix< M, N >", "structnum_1_1small__matrix.html", null ],
    [ "num::small_vec< N >", "structnum_1_1small__vec.html", null ],
    [ "num::solver_result", "structnum_1_1solver__result.html", null ],
    [ "num::linear::sparse_csr_mat< Mat >", "classnum_1_1linear_1_1sparse__csr__mat.html", null ],
    [ "num::operators::sparse_op", "structnum_1_1operators_1_1sparse__op.html", null ],
    [ "num::sparse_resolvent_options", "structnum_1_1sparse__resolvent__options.html", null ],
    [ "num::sparse_resolvent_solver", "classnum_1_1sparse__resolvent__solver.html", null ],
    [ "num::sph_kernel< Dim >", "structnum_1_1sph__kernel.html", null ],
    [ "num::detail::SpikyDW< Dim >", "structnum_1_1detail_1_1SpikyDW.html", null ],
    [ "num::detail::SpikyDW< 2 >", "structnum_1_1detail_1_1SpikyDW_3_012_01_4.html", null ],
    [ "num::detail::SpikyDW< 3 >", "structnum_1_1detail_1_1SpikyDW_3_013_01_4.html", null ],
    [ "num::spmat", "classnum_1_1spmat.html", null ],
    [ "num::linear::sq_mat< Mat >", "classnum_1_1linear_1_1sq__mat.html", null ],
    [ "num::linear::props_detail::square_tag< P >", "structnum_1_1linear_1_1props__detail_1_1square__tag.html", null ],
    [ "num::linear::props_detail::square_tag< Ax >", "structnum_1_1linear_1_1props__detail_1_1square__tag.html", [
      [ "num::linear::structured_mat< Mat, Ax >", "classnum_1_1linear_1_1structured__mat.html", null ]
    ] ],
    [ "num::step_end", "structnum_1_1step__end.html", null ],
    [ "num::law::strongest< List >", "structnum_1_1law_1_1strongest.html", null ],
    [ "num::law::strongest< math::type_list< L > >", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_01L_01_4_01_4.html", null ],
    [ "num::law::strongest< math::type_list< L, Rest... > >", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_01L_00_01Rest_8_8_8_01_4_01_4.html", null ],
    [ "num::law::strongest< math::type_list<> >", "structnum_1_1law_1_1strongest_3_01math_1_1type__list_3_4_01_4.html", null ],
    [ "num::operators::structured_op< Op, Ax >", "classnum_1_1operators_1_1structured__op.html", null ],
    [ "num::operators::sum_op< Lhs, Rhs >", "classnum_1_1operators_1_1sum__op.html", null ],
    [ "num::svd_result", "structnum_1_1svd__result.html", null ],
    [ "num::symplectic_result", "structnum_1_1symplectic__result.html", null ],
    [ "num::symplectic_step", "structnum_1_1symplectic__step.html", null ],
    [ "num::talbot_quadrature", "structnum_1_1talbot__quadrature.html", null ],
    [ "num::kernel::contract::throughput_t", "structnum_1_1kernel_1_1contract_1_1throughput__t.html", null ],
    [ "num::linear::tri_mat< Vec >", "classnum_1_1linear_1_1tri__mat.html", null ],
    [ "std::true_type", null, [
      [ "num::scalars::is_complex< std::complex< T > >", "structnum_1_1scalars_1_1is__complex_3_01std_1_1complex_3_01T_01_4_01_4.html", null ]
    ] ],
    [ "num::math::type_list< Ts >", "structnum_1_1math_1_1type__list.html", null ],
    [ "num::markov::umbrella_stats", "structnum_1_1markov_1_1umbrella__stats.html", null ],
    [ "num::markov::umbrella_window", "structnum_1_1markov_1_1umbrella__window.html", null ],
    [ "num::umfpack_factor", "classnum_1_1umfpack__factor.html", null ],
    [ "num::vec2_view", "structnum_1_1vec2__view.html", null ],
    [ "num::vector_field_3d", "structnum_1_1vector__field__3d.html", null ],
    [ "num::verlet_list_2d< scalar >", "classnum_1_1verlet__list__2d.html", null ],
    [ "num::math::zero_like_t", "structnum_1_1math_1_1zero__like__t.html", null ],
    [ "num::space::zero_sum", "structnum_1_1space_1_1zero__sum.html", null ]
];