var searchData=
[
  ['sample_2ehpp_0',['sample.hpp',['../sample_8hpp.html',1,'']]],
  ['scalar_2ehpp_1',['scalar.hpp',['../scalar_8hpp.html',1,'']]],
  ['scalar_5ffield_5f2d_2ehpp_2',['scalar_field_2d.hpp',['../scalar__field__2d_8hpp.html',1,'']]],
  ['selection_2ehpp_3',['selection.hpp',['../selection_8hpp.html',1,'']]],
  ['small_5fmatrix_2ehpp_4',['small_matrix.hpp',['../small__matrix_8hpp.html',1,'']]],
  ['solve_2ehpp_5',['solve.hpp',['../linear_2graph_2randommat_2solve_8hpp.html',1,'(Global Namespace)'],['../solve_2solve_8hpp.html',1,'(Global Namespace)']]],
  ['solve_2emd_6',['solve.md',['../solve_8md.html',1,'']]],
  ['solver_2dbest_2dpractices_2emd_7',['solver-best-practices.md',['../solver-best-practices_8md.html',1,'']]],
  ['solver_5fresult_2ehpp_8',['solver_result.hpp',['../solver__result_8hpp.html',1,'']]],
  ['solvers_2ehpp_9',['solvers.hpp',['../solvers_8hpp.html',1,'']]],
  ['sparse_2ehpp_10',['sparse.hpp',['../linear_2sparse_2sparse_8hpp.html',1,'(Global Namespace)'],['../kernel_2sparse_8hpp.html',1,'(Global Namespace)']]],
  ['sparse_5fjson_2ehpp_11',['sparse_json.hpp',['../sparse__json_8hpp.html',1,'']]],
  ['sparse_5fop_2ehpp_12',['sparse_op.hpp',['../sparse__op_8hpp.html',1,'']]],
  ['sparse_5fresolvent_2ecpp_13',['sparse_resolvent.cpp',['../sparse__resolvent_8cpp.html',1,'']]],
  ['sparse_5fresolvent_2ehpp_14',['sparse_resolvent.hpp',['../sparse__resolvent_8hpp.html',1,'']]],
  ['spatial_2ehpp_15',['spatial.hpp',['../spatial_8hpp.html',1,'']]],
  ['spatial_2emd_16',['spatial.md',['../spatial_8md.html',1,'']]],
  ['spectral_2emd_17',['spectral.md',['../spectral_8md.html',1,'']]],
  ['sph_2dkernel_2emd_18',['sph-kernel.md',['../sph-kernel_8md.html',1,'']]],
  ['sph_5fkernel_2ehpp_19',['sph_kernel.hpp',['../sph__kernel_8hpp.html',1,'']]],
  ['stats_2ehpp_20',['stats.hpp',['../stats_8hpp.html',1,'']]],
  ['stats_2emd_21',['stats.md',['../stats_8md.html',1,'']]],
  ['stencil_2dhof_2emd_22',['stencil-hof.md',['../stencil-hof_8md.html',1,'']]],
  ['stencil_2ehpp_23',['stencil.hpp',['../stencil_8hpp.html',1,'']]],
  ['steps_2ehpp_24',['steps.hpp',['../steps_8hpp.html',1,'']]],
  ['stochastic_2emd_25',['stochastic.md',['../stochastic_8md.html',1,'']]],
  ['structures_2ehpp_26',['structures.hpp',['../structures_8hpp.html',1,'']]],
  ['structures_2emd_27',['structures.md',['../structures_8md.html',1,'']]],
  ['subspace_2ehpp_28',['subspace.hpp',['../core_2math_2subspace_8hpp.html',1,'(Global Namespace)'],['../linear_2subspace_8hpp.html',1,'(Global Namespace)']]],
  ['sum_2ehpp_29',['sum.hpp',['../sum_8hpp.html',1,'']]],
  ['svd_2ehpp_30',['svd.hpp',['../svd_8hpp.html',1,'']]]
];
