# Optional SuiteSparse sparse-direct backends.
# KLU is LGPL-2.1-or-later; AMD and COLAMD are BSD-3-Clause. Numerics does not
# vendor these components and links to a separately installed shared library.
if(NOT NUMERICS_USE_SUITESPARSE)
    message(STATUS "SuiteSparse sparse-direct backends: disabled")
    return()
endif()

find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
    pkg_check_modules(KLU QUIET IMPORTED_TARGET klu)
    pkg_check_modules(UMFPACK QUIET IMPORTED_TARGET umfpack)
endif()

if(TARGET PkgConfig::KLU)
    target_link_libraries(numerics_backend_suitesparse INTERFACE PkgConfig::KLU)
    target_compile_definitions(numerics_backend_suitesparse INTERFACE NUMERICS_HAS_KLU)
    set(NUMERICS_HAS_KLU ON CACHE INTERNAL "")
    message(STATUS "SuiteSparse KLU: found via pkg-config (${KLU_VERSION})")
else()
    find_path(KLU_INCLUDE_DIR klu.h PATH_SUFFIXES suitesparse)
    find_library(KLU_LIBRARY NAMES klu)
    if(KLU_INCLUDE_DIR AND KLU_LIBRARY)
        target_include_directories(numerics_backend_suitesparse INTERFACE ${KLU_INCLUDE_DIR})
        target_link_libraries(numerics_backend_suitesparse INTERFACE ${KLU_LIBRARY})
        target_compile_definitions(numerics_backend_suitesparse INTERFACE NUMERICS_HAS_KLU)
        set(NUMERICS_HAS_KLU ON CACHE INTERNAL "")
        message(STATUS "SuiteSparse KLU: found (${KLU_LIBRARY})")
    else()
        set(NUMERICS_HAS_KLU OFF CACHE INTERNAL "")
        message(STATUS "SuiteSparse KLU: not found; sparse-direct backend unavailable")
        message(STATUS "                 Install: apt install libsuitesparse-dev | brew install suite-sparse")
    endif()
endif()

if(TARGET PkgConfig::UMFPACK)
    target_link_libraries(numerics_backend_suitesparse INTERFACE PkgConfig::UMFPACK)
    target_compile_definitions(numerics_backend_suitesparse INTERFACE NUMERICS_HAS_UMFPACK)
    set(NUMERICS_HAS_UMFPACK ON CACHE INTERNAL "")
    message(STATUS "SuiteSparse UMFPACK: found via pkg-config (${UMFPACK_VERSION})")
else()
    find_path(UMFPACK_INCLUDE_DIR umfpack.h PATH_SUFFIXES suitesparse)
    find_library(UMFPACK_LIBRARY NAMES umfpack)
    if(UMFPACK_INCLUDE_DIR AND UMFPACK_LIBRARY)
        target_include_directories(numerics_backend_suitesparse INTERFACE ${UMFPACK_INCLUDE_DIR})
        target_link_libraries(numerics_backend_suitesparse INTERFACE ${UMFPACK_LIBRARY})
        target_compile_definitions(numerics_backend_suitesparse INTERFACE NUMERICS_HAS_UMFPACK)
        set(NUMERICS_HAS_UMFPACK ON CACHE INTERNAL "")
        message(STATUS "SuiteSparse UMFPACK: found (${UMFPACK_LIBRARY})")
    else()
        set(NUMERICS_HAS_UMFPACK OFF CACHE INTERNAL "")
        message(STATUS "SuiteSparse UMFPACK: not found")
    endif()
endif()
