numerics: tdse::TDSESolver Class Reference
tdse::TDSESolver Class Reference
#include <sim.hpp>
Public Member Functions
TDSESolver (int N, double L, double dt)
void set_potential (Potential p, double param=0.0)
Build potential and recompute Thomas factorisations.
void init_gaussian (double x0, double y0, double kx, double ky, double sigma)
void set_mode (int k)
Set psi to the k-th eigenmode (modes must be computed first).
void step ()
Advance one full time step (Strang splitting).
void compute_modes (int k=8)
int at (int i, int j) const
double prob (int i, int j) const
double phase_ang (int i, int j) const
double compute_norm () const
integral|psi|^2 dA (Gauss-Legendre over each grid strip).
double compute_energy () const
<psi|H|psi> using 5-point Laplacian and the potential.
void renormalize ()
Public Attributes
int N
Interior grid points per axis.
double L
Domain length ([0,L]x[0,L])
double h
Grid spacing = L/(N+1)
double dt
Time step.
num::CVector psi
NxN wavefunction (complex, length N^2)
num::Vector V
NxN potential (real, length N^2)
std::vector< EigenMode > modes
bool modes_ready = false
Stats stats
Detailed Description
Definition at line 82 of file sim.hpp.
Constructor & Destructor Documentation
TDSESolver()
tdse::TDSESolver::TDSESolver (int N, double L, double dt)
Definition at line 28 of file sim.cpp.
References init_gaussian().
Member Function Documentation
at()
int tdse::TDSESolver::at (int i, int j) const inline
Definition at line 121 of file sim.hpp.
References N.
Referenced by init_gaussian(), phase_ang(), prob(), and set_potential().
compute_energy()
double tdse::TDSESolver::compute_energy () const
<psi|H|psi> using 5-point Laplacian and the potential.
Definition at line 181 of file sim.cpp.
References h, num::laplacian_stencil_2d(), N, psi, num::BasicVector< T >::size(), and V.
compute_modes()
void tdse::TDSESolver::compute_modes (int k = 8)
Run Lanczos to find the k lowest eigenstates of H. For CircularWell also fills EigenMode::exact_energy via Bessel zero search.
Definition at line 204 of file sim.cpp.
References num::bessel_j(), num::brent(), tdse::CircularWell, num::e, tdse::EigenMode::energy, h, L, num::lanczos(), num::laplacian_stencil_2d(), modes, modes_ready, N, tdse::Stats::n_modes, tdse::EigenMode::phi, stats, num::to_idx(), and V.
compute_norm()
double tdse::TDSESolver::compute_norm () const
integral|psi|^2 dA (Gauss-Legendre over each grid strip).
Definition at line 176 of file sim.cpp.
References h, num::norm(), and psi.
init_gaussian()
void tdse::TDSESolver::init_gaussian (double x0, double y0, double kx, double ky, double sigma)
Gaussian wavepacket: psi = A*exp(-(r-r0)^2/sigma^2)*exp(i*k*r), then normalised.
Definition at line 116 of file sim.cpp.
References at(), h, N, num::phi, psi, and renormalize().
Referenced by TDSESolver().
phase_ang()
double tdse::TDSESolver::phase_ang (int i, int j) const inline
Definition at line 129 of file sim.hpp.
References at(), and psi.
Referenced by main().
prob()
double tdse::TDSESolver::prob (int i, int j) const inline
Definition at line 125 of file sim.hpp.
References at(), and psi.
Referenced by main().
renormalize()
void tdse::TDSESolver::renormalize ()
Definition at line 197 of file sim.cpp.
References h, num::norm(), psi, and num::scale().
Referenced by init_gaussian().
set_mode()
void tdse::TDSESolver::set_mode (int k)
Set psi to the k-th eigenmode (modes must be computed first).
Definition at line 134 of file sim.cpp.
References modes, modes_ready, N, num::phi, and psi.
set_potential()
void tdse::TDSESolver::set_potential (Potential p, double param = 0.0)
Build potential and recompute Thomas factorisations.
Definition at line 45 of file sim.cpp.
References at(), tdse::Barrier, tdse::CircularWell, tdse::DoubleSlit, h, tdse::Harmonic, L, modes_ready, N, num::scale(), and V.
step()
void tdse::TDSESolver::step ()
Advance one full time step (Strang splitting).
Definition at line 161 of file sim.cpp.
References dt, stats, and tdse::Stats::step_ms.
Referenced by main().
Member Data Documentation
dt
double tdse::TDSESolver::dt
Time step.
Definition at line 87 of file sim.hpp.
Referenced by step().
h
double tdse::TDSESolver::h
Grid spacing = L/(N+1)
Definition at line 86 of file sim.hpp.
Referenced by compute_energy(), compute_modes(), compute_norm(), init_gaussian(), renormalize(), and set_potential().
L
double tdse::TDSESolver::L
Domain length ([0,L]x[0,L])
Definition at line 85 of file sim.hpp.
Referenced by compute_modes(), and set_potential().
modes
std::vector<EigenMode> tdse::TDSESolver::modes
Definition at line 92 of file sim.hpp.
Referenced by compute_modes(), and set_mode().
modes_ready
bool tdse::TDSESolver::modes_ready = false
Definition at line 93 of file sim.hpp.
Referenced by compute_modes(), set_mode(), and set_potential().
N
int tdse::TDSESolver::N
Interior grid points per axis.
Definition at line 84 of file sim.hpp.
Referenced by at(), compute_energy(), compute_modes(), init_gaussian(), set_mode(), and set_potential().
psi
num::CVector tdse::TDSESolver::psi
NxN wavefunction (complex, length N^2)
Definition at line 89 of file sim.hpp.
Referenced by compute_energy(), compute_norm(), init_gaussian(), phase_ang(), prob(), renormalize(), and set_mode().
stats
Stats tdse::TDSESolver::stats
Definition at line 95 of file sim.hpp.
Referenced by compute_modes(), and step().
V
num::Vector tdse::TDSESolver::V
NxN potential (real, length N^2)
Definition at line 90 of file sim.hpp.
Referenced by compute_energy(), compute_modes(), and set_potential().
The documentation for this class was generated from the following files:
/home/runner/work/numerics/numerics/apps/tdse/include/tdse/sim.hpp
/home/runner/work/numerics/numerics/apps/tdse/src/sim.cpp