numerics: num::BasicVector< T > Class Template Reference
num::BasicVector< T > Class Template Reference
Dense vector with optional GPU storage, templated over scalar type T.
#include <vector.hpp>
Public Member Functions
BasicVector ()
BasicVector (idx n)
BasicVector (idx n, T val)
BasicVector (std::initializer_list< T > init)
~BasicVector ()
BasicVector (const BasicVector &o)
BasicVector (BasicVector &&o) noexcept
BasicVector & operator= (const BasicVector &o)
BasicVector & operator= (BasicVector &&o) noexcept
constexpr idx size () const noexcept
BasicVector & vec ()
Satisfy the VecField concept: a Vector is its own underlying vector.
const BasicVector & vec () const
T * data ()
const T * data () const
T & operator[] (idx i)
T operator[] (idx i) const
T * begin ()
T * end ()
const T * begin () const
const T * end () const
void to_gpu ()
void to_cpu ()
real * gpu_data ()
const real * gpu_data () const
bool on_gpu () const
Detailed Description
template<typename T>
class num::BasicVector< T >
Dense vector with optional GPU storage, templated over scalar type T.
Typical aliases:
num::Vector = BasicVector<real> – real-valued, full backend dispatch including GPU
num::CVector = BasicVector<cplx> – complex-valued, sequential only (no GPU)
All member functions are defined inline so the template is usable across translation units without explicit instantiation.
Definition at line 25 of file vector.hpp.
Constructor & Destructor Documentation
BasicVector() [1/6]
template<typename T > num::BasicVector< T >::BasicVector () inline
Definition at line 27 of file vector.hpp.
BasicVector() [2/6]
template<typename T > num::BasicVector< T >::BasicVector (idx n) inline explicit
Definition at line 31 of file vector.hpp.
BasicVector() [3/6]
template<typename T > num::BasicVector< T >::BasicVector (idx n, T val) inline
Definition at line 35 of file vector.hpp.
BasicVector() [4/6]
template<typename T > num::BasicVector< T >::BasicVector (std::initializer_list< T > init) inline
Definition at line 41 of file vector.hpp.
~BasicVector()
template<typename T > num::BasicVector< T >::~BasicVector () inline
Definition at line 47 of file vector.hpp.
References num::cuda::free().
BasicVector() [5/6]
template<typename T > num::BasicVector< T >::BasicVector (const BasicVector< T > & o) inline
Definition at line 54 of file vector.hpp.
BasicVector() [6/6]
template<typename T > num::BasicVector< T >::BasicVector (BasicVector< T > && o) inline noexcept
Definition at line 60 of file vector.hpp.
Member Function Documentation
begin() [1/2]
template<typename T > T * num::BasicVector< T >::begin () inline
Definition at line 114 of file vector.hpp.
Referenced by nbody::NBodySim::make_accel().
begin() [2/2]
template<typename T > const T * num::BasicVector< T >::begin () const inline
Definition at line 120 of file vector.hpp.
data() [1/2]
template<typename T > T * num::BasicVector< T >::data () inline
Definition at line 100 of file vector.hpp.
Referenced by num::backends::blas::axpy(), num::banded_gemv(), num::banded_lu_solve(), num::ScalarField2D::data(), num::ScalarField2D::data(), num::backends::blas::dot(), num::backends::lapack::eig_sym(), backends::opt::FFTPlanImpl::execute(), num::laplacian_stencil_2d_periodic(), num::backends::blas::matvec(), num::backends::blas::norm(), num::backends::blas::scale(), num::backends::lapack::svd(), and num::backends::lapack::thomas().
data() [2/2]
template<typename T > const T * num::BasicVector< T >::data () const inline
Definition at line 103 of file vector.hpp.
end() [1/2]
template<typename T > T * num::BasicVector< T >::end () inline
Definition at line 117 of file vector.hpp.
Referenced by nbody::NBodySim::make_accel().
end() [2/2]
template<typename T > const T * num::BasicVector< T >::end () const inline
Definition at line 123 of file vector.hpp.
gpu_data() [1/2]
template<typename T > real * num::BasicVector< T >::gpu_data () inline
Definition at line 148 of file vector.hpp.
Referenced by num::add(), num::backends::gpu::axpy(), num::backends::gpu::dot(), num::backends::gpu::matvec(), num::backends::gpu::norm(), num::backends::gpu::scale(), and num::thomas().
gpu_data() [2/2]
template<typename T > const real * num::BasicVector< T >::gpu_data () const inline
Definition at line 151 of file vector.hpp.
on_gpu()
template<typename T > bool num::BasicVector< T >::on_gpu () const inline
Definition at line 154 of file vector.hpp.
operator=() [1/2]
template<typename T > BasicVector & num::BasicVector< T >::operator= (BasicVector< T > && o) inline noexcept
Definition at line 77 of file vector.hpp.
References num::cuda::free().
operator=() [2/2]
template<typename T > BasicVector & num::BasicVector< T >::operator= (const BasicVector< T > & o) inline
Definition at line 68 of file vector.hpp.
operator[]() [1/2]
template<typename T > T & num::BasicVector< T >::operator[] (idx i) inline
Definition at line 107 of file vector.hpp.
operator[]() [2/2]
template<typename T > T num::BasicVector< T >::operator[] (idx i) const inline
Definition at line 110 of file vector.hpp.
size()
template<typename T > constexpr idx num::BasicVector< T >::size () const inline constexpr noexcept
Definition at line 92 of file vector.hpp.
Referenced by num::backends::seq::add(), num::add(), num::axpy(), num::backends::blas::axpy(), num::backends::gpu::axpy(), num::backends::omp::axpy(), num::backends::seq::axpy(), num::banded_gemv(), num::banded_lu_solve(), num::banded_solve(), backends::seq::bit_reverse(), num::cg(), num::cg_matfree(), tdse::TDSESolver::compute_energy(), backends::seq::cooley_tukey(), num::pde::diffusion_step_2d(), num::pde::diffusion_step_2d_4th_dirichlet(), num::pde::diffusion_step_2d_dirichlet(), num::dot(), num::backends::blas::dot(), num::backends::gpu::dot(), num::backends::omp::dot(), num::backends::seq::dot(), num::spectral::FFTPlan::execute(), num::quantum::expectation(), num::quantum::expectation_x(), num::quantum::expectation_y(), num::quantum::expectation_z(), num::spectral::fft(), backends::opt::fft(), backends::seq::fft(), num::gauss_seidel(), num::gmres(), num::spectral::ifft(), backends::opt::ifft(), backends::seq::ifft(), num::spectral::irfft(), num::jacobi(), num::norm(), num::backends::blas::norm(), num::backends::gpu::norm(), num::backends::seq::norm(), num::detail::normalise(), num::quantum::probabilities(), num::rayleigh_iteration(), backends::opt::rfft(), backends::seq::rfft(), num::spectral::rfft(), num::scale(), num::backends::blas::scale(), num::backends::gpu::scale(), num::backends::omp::scale(), num::backends::seq::scale(), num::ScalarField2D::size(), num::Vec2View::size(), num::Vec2ConstView::size(), num::sparse_matvec(), num::backends::lapack::thomas(), num::backends::seq::thomas(), and num::thomas().
to_cpu()
template<typename T > void num::BasicVector< T >::to_cpu () inline
Definition at line 138 of file vector.hpp.
References num::cuda::free(), and num::cuda::to_host().
Referenced by num::cg(), and num::thomas().
to_gpu()
template<typename T > void num::BasicVector< T >::to_gpu () inline
Definition at line 129 of file vector.hpp.
References num::cuda::alloc(), and num::cuda::to_device().
Referenced by num::cg(), and num::thomas().
vec() [1/2]
template<typename T > BasicVector & num::BasicVector< T >::vec () inline
Satisfy the VecField concept: a Vector is its own underlying vector.
Definition at line 97 of file vector.hpp.
Referenced by num::ode::advance(), and num::ode::advance().
vec() [2/2]
template<typename T > const BasicVector & num::BasicVector< T >::vec () const inline
Definition at line 98 of file vector.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/numerics/numerics/include/core/vector.hpp