numerics: physics::FluidSolver Class Reference
physics::FluidSolver Class Reference
#include <fluid.hpp>
Public Member Functions
FluidSolver (const FluidParams &params)
void add_particle (float x, float y, float vx, float vy, float temperature)
void add_body (const RigidBody &body)
void clear ()
void step ()
const std::vector< Particle > & particles () const
const std::vector< RigidBody > & bodies () const
std::vector< RigidBody > & bodies ()
const FluidParams & params () const
float min_temp () const
float max_temp () const
Detailed Description
Definition at line 67 of file fluid.hpp.
Constructor & Destructor Documentation
FluidSolver()
physics::FluidSolver::FluidSolver (const FluidParams & params) explicit
Definition at line 23 of file fluid.cpp.
Member Function Documentation
add_body()
void physics::FluidSolver::add_body (const RigidBody & body)
Definition at line 49 of file fluid.cpp.
add_particle()
void physics::FluidSolver::add_particle (float x, float y, float vx, float vy, float temperature)
Definition at line 31 of file fluid.cpp.
References physics::FluidParams::rho0, and physics::Particle::x.
bodies() [1/2]
std::vector< RigidBody > & physics::FluidSolver::bodies () inline
Definition at line 85 of file fluid.hpp.
bodies() [2/2]
const std::vector< RigidBody > & physics::FluidSolver::bodies () const inline
Definition at line 82 of file fluid.hpp.
Referenced by main().
clear()
void physics::FluidSolver::clear ()
Definition at line 52 of file fluid.cpp.
max_temp()
float physics::FluidSolver::max_temp () const inline
Definition at line 95 of file fluid.hpp.
Referenced by main().
min_temp()
float physics::FluidSolver::min_temp () const inline
Definition at line 92 of file fluid.hpp.
Referenced by main().
params()
const FluidParams & physics::FluidSolver::params () const inline
Definition at line 88 of file fluid.hpp.
particles()
const std::vector< Particle > & physics::FluidSolver::particles () const inline
Definition at line 79 of file fluid.hpp.
Referenced by main().
step()
void physics::FluidSolver::step ()
Advance the simulation by one timestep (params_.dt). Dispatches to backends::seq or backends::omp based on params_.policy.
Definition at line 59 of file fluid.cpp.
References physics::FluidParams::alpha_T, physics::backends::omp::body_collisions(), physics::backends::seq::body_collisions(), physics::SpatialHash::build(), physics::backends::omp::compute_density_pressure(), physics::backends::seq::compute_density_pressure(), physics::backends::omp::compute_forces(), physics::backends::seq::compute_forces(), physics::backends::omp::enforce_boundaries(), physics::backends::seq::enforce_boundaries(), physics::FluidParams::h, physics::FluidParams::h_conv, physics::backends::omp::heat_compute(), physics::backends::seq::heat_compute(), physics::backends::omp::integrate(), physics::backends::seq::integrate(), physics::backends::seq::integrate_bodies(), physics::FluidParams::mass, num::omp, physics::FluidParams::policy, physics::backends::omp::update_temp_range(), and physics::backends::seq::update_temp_range().
Referenced by main().
The documentation for this class was generated from the following files:
/home/runner/work/numerics/numerics/apps/fluid_sim/fluid.hpp
/home/runner/work/numerics/numerics/apps/fluid_sim/fluid.cpp
/home/runner/work/numerics/numerics/apps/fluid_sim/src/fluid.cpp