numerics: num::ScalarField2D Class Reference
num::ScalarField2D Class Reference
#include <scalar_field_2d.hpp>
Public Member Functions
ScalarField2D (Grid2D g)
template<typename F >
ScalarField2D (Grid2D g, F &&f)
Construct and fill from callable f(x, y) -> real.
const Grid2D & grid () const
int N () const
double h () const
real & operator() (int i, int j)
real operator() (int i, int j) const
template<typename F >
void fill (F &&f)
Fill every interior node (i,j) with f((i+1)*h, (j+1)*h).
Vector & vec ()
Satisfy VecField concept: exposes the underlying flat vector.
const Vector & vec () const
real * data ()
const real * data () const
idx size () const
Detailed Description
Definition at line 21 of file scalar_field_2d.hpp.
Constructor & Destructor Documentation
ScalarField2D() [1/2]
num::ScalarField2D::ScalarField2D (Grid2D g) inline explicit
Definition at line 23 of file scalar_field_2d.hpp.
ScalarField2D() [2/2]
template<typename F > num::ScalarField2D::ScalarField2D (Grid2D g, F && f) inline
Construct and fill from callable f(x, y) -> real.
Definition at line 29 of file scalar_field_2d.hpp.
References fill().
Member Function Documentation
data() [1/2]
real * num::ScalarField2D::data () inline
Definition at line 50 of file scalar_field_2d.hpp.
References num::BasicVector< T >::data().
data() [2/2]
const real * num::ScalarField2D::data () const inline
Definition at line 51 of file scalar_field_2d.hpp.
References num::BasicVector< T >::data().
fill()
template<typename F > void num::ScalarField2D::fill (F && f) inline
Fill every interior node (i,j) with f((i+1)*h, (j+1)*h).
Definition at line 40 of file scalar_field_2d.hpp.
References num::Grid2D::N, num::Grid2D::x(), and num::Grid2D::y().
Referenced by ScalarField2D().
grid()
const Grid2D & num::ScalarField2D::grid () const inline
Definition at line 31 of file scalar_field_2d.hpp.
h()
double num::ScalarField2D::h () const inline
Definition at line 33 of file scalar_field_2d.hpp.
References num::Grid2D::h.
Referenced by num::col_slice(), num::fill_grid(), num::plt::heatmap(), num::row_slice(), and num::sample_2d_periodic().
N()
int num::ScalarField2D::N () const inline
Definition at line 32 of file scalar_field_2d.hpp.
References num::Grid2D::N.
Referenced by num::col_slice(), num::pde::diffusion_step_2d_4th_dirichlet(), num::pde::diffusion_step_2d_dirichlet(), num::fill_grid(), num::plt::heatmap(), num::laplacian_stencil_2d_4th(), num::laplacian_stencil_2d_periodic(), num::row_slice(), and num::sample_2d_periodic().
operator()() [1/2]
real & num::ScalarField2D::operator() (int i, int j) inline
Definition at line 35 of file scalar_field_2d.hpp.
References num::Grid2D::N.
operator()() [2/2]
real num::ScalarField2D::operator() (int i, int j) const inline
Definition at line 36 of file scalar_field_2d.hpp.
References num::Grid2D::N.
size()
idx num::ScalarField2D::size () const inline
Definition at line 52 of file scalar_field_2d.hpp.
References num::BasicVector< T >::size().
vec() [1/2]
Vector & num::ScalarField2D::vec () inline
Satisfy VecField concept: exposes the underlying flat vector.
Definition at line 47 of file scalar_field_2d.hpp.
Referenced by num::col_slice(), num::pde::diffusion_step_2d_4th_dirichlet(), num::pde::diffusion_step_2d_dirichlet(), num::fill_grid(), num::laplacian_stencil_2d_4th(), num::laplacian_stencil_2d_periodic(), num::row_slice(), and num::sample_2d_periodic().
vec() [2/2]
const Vector & num::ScalarField2D::vec () const inline
Definition at line 48 of file scalar_field_2d.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/numerics/numerics/include/pde/scalar_field_2d.hpp