numerics: physics::ElectricSolver Class Reference
physics::ElectricSolver Class Reference
#include <sim.hpp>
Static Public Member Functions
static num::SolverResult solve_potential (ScalarField3D &phi, const ScalarField3D &sigma, const std::vector< ElectrodeBC > &bcs, double tol=1e-6, int max_iter=500)
static ScalarField3D joule_heating (const ScalarField3D &sigma, const ScalarField3D &phi)
Compute Joule heating power density Q = sigma*|grad(phi)|^2 [W/m^3].
Detailed Description
Definition at line 29 of file sim.hpp.
Member Function Documentation
joule_heating()
ScalarField3D physics::ElectricSolver::joule_heating (const ScalarField3D & sigma, const ScalarField3D & phi) static
Compute Joule heating power density Q = sigma*|grad(phi)|^2 [W/m^3].
Definition at line 22 of file sim.cpp.
References num::Grid3D::dx(), num::ScalarField3D::grid(), num::Grid3D::nx(), num::Grid3D::ny(), num::Grid3D::nz(), and num::Grid3D::set().
solve_potential()
num::SolverResult physics::ElectricSolver::solve_potential (ScalarField3D & phi, const ScalarField3D & sigma, const std::vector< ElectrodeBC > & bcs, double tol = 1e-6, int max_iter = 500) static
Solve div(sigma*grad(phi)) = 0 with Dirichlet BCs at electrode nodes, Neumann (zero normal flux) on all remaining boundaries.
Uses symmetric elimination so the system is SPD (CG converges).
Definition at line 9 of file sim.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
/home/runner/work/numerics/numerics/apps/em_demo/include/em_demo/sim.hpp
/home/runner/work/numerics/numerics/apps/em_demo/src/sim.cpp