numerics: num::SparseMatrix Class Reference
num::SparseMatrix Class Reference
Sparse matrix in Compressed Sparse Row (CSR) format.
#include <sparse.hpp>
Public Member Functions
SparseMatrix (idx n_rows, idx n_cols, std::vector< real > vals, std::vector< idx > col_idx, std::vector< idx > row_ptr)
Construct from raw CSR arrays (takes ownership)
idx n_rows () const
idx n_cols () const
idx nnz () const
real operator() (idx i, idx j) const
Element access A(i,j); returns 0 if outside stored pattern – O(nnz/n)
const real * values () const
const idx * col_idx () const
const idx * row_ptr () const
Static Public Member Functions
static SparseMatrix from_triplets (idx n_rows, idx n_cols, const std::vector< idx > &rows, const std::vector< idx > &cols, const std::vector< real > &vals)
Build from coordinate (COO / triplet) lists.
Detailed Description
Sparse matrix in Compressed Sparse Row (CSR) format.
Non-zero values for row i are stored in vals_[row_ptr_[i] .. row_ptr_[i+1]). Corresponding column indices are in col_idx_[row_ptr_[i] .. row_ptr_[i+1]).
Definition at line 15 of file sparse.hpp.
Constructor & Destructor Documentation
SparseMatrix()
num::SparseMatrix::SparseMatrix (idx n_rows, idx n_cols, std::vector< real > vals, std::vector< idx > col_idx, std::vector< idx > row_ptr)
Construct from raw CSR arrays (takes ownership)
Definition at line 8 of file sparse.cpp.
Member Function Documentation
col_idx()
const idx * num::SparseMatrix::col_idx () const inline
Definition at line 50 of file sparse.hpp.
Referenced by num::sparse_matvec().
from_triplets()
SparseMatrix num::SparseMatrix::from_triplets (idx n_rows, idx n_cols, const std::vector< idx > & rows, const std::vector< idx > & cols, const std::vector< real > & vals) static
Build from coordinate (COO / triplet) lists.
Duplicate (row, col) entries are summed. Entries need not be sorted.
Definition at line 26 of file sparse.cpp.
References n_cols(), n_rows(), nnz(), and row_ptr().
Referenced by num::pde::backward_euler_matrix(), and num::pde::laplacian_sparse_2d().
n_cols()
idx num::SparseMatrix::n_cols () const inline
Definition at line 36 of file sparse.hpp.
Referenced by from_triplets(), num::gmres(), and num::sparse_matvec().
n_rows()
idx num::SparseMatrix::n_rows () const inline
Definition at line 33 of file sparse.hpp.
Referenced by num::expv(), from_triplets(), num::gmres(), and num::sparse_matvec().
nnz()
idx num::SparseMatrix::nnz () const inline
Definition at line 39 of file sparse.hpp.
Referenced by from_triplets().
operator()()
real num::SparseMatrix::operator() (idx i, idx j) const
Element access A(i,j); returns 0 if outside stored pattern – O(nnz/n)
Definition at line 117 of file sparse.cpp.
row_ptr()
const idx * num::SparseMatrix::row_ptr () const inline
Definition at line 53 of file sparse.hpp.
Referenced by from_triplets(), and num::sparse_matvec().
values()
const real * num::SparseMatrix::values () const inline
Definition at line 47 of file sparse.hpp.
Referenced by num::sparse_matvec().
The documentation for this class was generated from the following files:
/home/runner/work/numerics/numerics/include/linalg/sparse/sparse.hpp
/home/runner/work/numerics/numerics/src/linalg/sparse/sparse.cpp