numerics: num::spectral::FFTPlan Class Reference
num::spectral::FFTPlan Class Reference
Precomputed plan for repeated complex transforms of a fixed size.
#include <fft.hpp>
Public Member Functions
FFTPlan (int n, bool forward=true, FFTBackend b=default_fft_backend)
~FFTPlan ()
FFTPlan (const FFTPlan &)=delete
FFTPlan & operator= (const FFTPlan &)=delete
void execute (const CVector &in, CVector &out) const
int size () const
FFTBackend backend () const
Detailed Description
Precomputed plan for repeated complex transforms of a fixed size.
num::spectral::FFTPlan plan(1024);          // forward, default backend
for (auto& frame : frames)
    plan.execute(frame, spectrum);           // O(n log n), no allocation
Definition at line 108 of file fft.hpp.
Constructor & Destructor Documentation
FFTPlan() [1/2]
num::spectral::FFTPlan::FFTPlan (int n, bool forward = true, FFTBackend b = default_fft_backend) explicit
Parameters
n Transform size (must be power of two for FFTBackend::seq)
forward true = forward DFT, false = inverse DFT
b Backend to use (default: default_fft_backend)
Definition at line 116 of file fft.cpp.
References num::spectral::fftw, num::spectral::simd, and num::spectral::stdsimd.
~FFTPlan()
num::spectral::FFTPlan::~FFTPlan ()
Definition at line 140 of file fft.cpp.
References num::spectral::fftw, num::spectral::simd, and num::spectral::stdsimd.
FFTPlan() [2/2]
num::spectral::FFTPlan::FFTPlan (const FFTPlan &) delete
Member Function Documentation
backend()
FFTBackend num::spectral::FFTPlan::backend () const inline
Definition at line 127 of file fft.hpp.
execute()
void num::spectral::FFTPlan::execute (const CVector & in, CVector & out) const
Definition at line 162 of file fft.cpp.
References execute(), num::spectral::fftw, num::spectral::simd, num::BasicVector< T >::size(), and num::spectral::stdsimd.
Referenced by execute().
operator=()
FFTPlan & num::spectral::FFTPlan::operator= (const FFTPlan &) delete
size()
int num::spectral::FFTPlan::size () const inline
Definition at line 124 of file fft.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/numerics/numerics/include/spectral/fft.hpp
/home/runner/work/numerics/numerics/src/spectral/fft.cpp