numerics: num::Matrix Class Reference
num::Matrix Class Reference
Dense row-major matrix with optional GPU storage.
#include <matrix.hpp>
Public Member Functions
Matrix ()
Matrix (idx rows, idx cols)
Matrix (idx rows, idx cols, real val)
~Matrix ()
Matrix (const Matrix &)
Matrix (Matrix &&) noexcept
Matrix & operator= (const Matrix &)
Matrix & operator= (Matrix &&) noexcept
constexpr idx rows () const noexcept
constexpr idx cols () const noexcept
constexpr idx size () const noexcept
real * data ()
const real * data () const
real & operator() (idx i, idx j)
real operator() (idx i, idx j) const
void to_gpu ()
void to_cpu ()
real * gpu_data ()
const real * gpu_data () const
bool on_gpu () const
Detailed Description
Dense row-major matrix with optional GPU storage.
Definition at line 12 of file matrix.hpp.
Constructor & Destructor Documentation
Matrix() [1/5]
num::Matrix::Matrix () inline
Definition at line 14 of file matrix.hpp.
Matrix() [2/5]
num::Matrix::Matrix (idx rows, idx cols)
Definition at line 23 of file matrix.cpp.
Matrix() [3/5]
num::Matrix::Matrix (idx rows, idx cols, real val)
Definition at line 28 of file matrix.cpp.
References size().
~Matrix()
num::Matrix::~Matrix ()
Definition at line 35 of file matrix.cpp.
References num::cuda::free().
Matrix() [4/5]
num::Matrix::Matrix (const Matrix & o)
Definition at line 40 of file matrix.cpp.
References size().
Matrix() [5/5]
num::Matrix::Matrix (Matrix && o) noexcept
Definition at line 47 of file matrix.cpp.
Member Function Documentation
cols()
constexpr idx num::Matrix::cols () const inline constexpr noexcept
Definition at line 25 of file matrix.hpp.
Referenced by num::cg(), num::backends::lapack::eig_sym(), num::backends::omp::eig_sym(), num::backends::seq::eig_sym(), num::gauss_seidel(), num::gmres(), num::inverse_iteration(), num::jacobi(), num::lu_solve(), num::backends::blas::matmul(), num::backends::gpu::matmul(), num::backends::omp::matmul(), num::backends::seq::matmul(), num::backends::seq::matmul_blocked(), num::backends::seq::matmul_register_blocked(), num::backends::blas::matvec(), num::backends::gpu::matvec(), num::backends::omp::matvec(), num::backends::seq::matvec(), num::kernel::subspace::mgs_orthogonalize(), num::power_iteration(), num::backends::lapack::qr(), num::backends::seq::qr(), num::qr_solve(), num::rayleigh_iteration(), num::backends::lapack::svd(), num::backends::seq::svd(), num::svd_truncated(), num::kernel::dense::trsv_lower(), and num::kernel::dense::trsv_upper().
data() [1/2]
real * num::Matrix::data () inline
Definition at line 28 of file matrix.hpp.
Referenced by num::backends::lapack::eig_sym(), num::kernel::dense::ger(), num::backends::lapack::lu(), num::backends::blas::matadd(), num::backends::omp::matadd(), num::backends::seq::matadd(), num::backends::blas::matmul(), num::backends::omp::matmul(), num::backends::seq::matmul_blocked(), num::backends::seq::matmul_register_blocked(), num::backends::blas::matvec(), num::kernel::subspace::mgs_orthogonalize(), num::backends::lapack::qr(), num::backends::lapack::svd(), num::kernel::dense::trsv_lower(), and num::kernel::dense::trsv_upper().
data() [2/2]
const real * num::Matrix::data () const inline
Definition at line 29 of file matrix.hpp.
gpu_data() [1/2]
real * num::Matrix::gpu_data () inline
Definition at line 35 of file matrix.hpp.
Referenced by num::backends::gpu::matmul(), and num::backends::gpu::matvec().
gpu_data() [2/2]
const real * num::Matrix::gpu_data () const inline
Definition at line 36 of file matrix.hpp.
on_gpu()
bool num::Matrix::on_gpu () const inline
Definition at line 37 of file matrix.hpp.
operator()() [1/2]
real & num::Matrix::operator() (idx i, idx j) inline
Definition at line 30 of file matrix.hpp.
operator()() [2/2]
real num::Matrix::operator() (idx i, idx j) const inline
Definition at line 31 of file matrix.hpp.
operator=() [1/2]
Matrix & num::Matrix::operator= (const Matrix & o)
Definition at line 56 of file matrix.cpp.
References size().
operator=() [2/2]
Matrix & num::Matrix::operator= (Matrix && o) noexcept
Definition at line 66 of file matrix.cpp.
References num::cuda::free().
rows()
constexpr idx num::Matrix::rows () const inline constexpr noexcept
Definition at line 24 of file matrix.hpp.
Referenced by num::kernel::subspace::DenseOp::apply(), num::cg(), num::backends::lapack::eig_sym(), num::backends::omp::eig_sym(), num::backends::seq::eig_sym(), num::gauss_seidel(), num::gmres(), num::inverse_iteration(), num::jacobi(), num::backends::lapack::lu(), num::backends::seq::lu(), num::lu_det(), num::lu_inv(), num::lu_solve(), num::lu_solve(), num::backends::blas::matmul(), num::backends::gpu::matmul(), num::backends::omp::matmul(), num::backends::seq::matmul(), num::backends::seq::matmul_blocked(), num::backends::seq::matmul_register_blocked(), num::backends::blas::matvec(), num::backends::gpu::matvec(), num::backends::omp::matvec(), num::backends::seq::matvec(), num::kernel::subspace::mgs_orthogonalize(), num::power_iteration(), num::backends::lapack::qr(), num::backends::seq::qr(), num::qr_solve(), num::rayleigh_iteration(), num::backends::lapack::svd(), num::backends::seq::svd(), num::svd_truncated(), num::kernel::dense::trsv_lower(), and num::kernel::dense::trsv_upper().
size()
constexpr idx num::Matrix::size () const inline constexpr noexcept
Definition at line 26 of file matrix.hpp.
Referenced by num::backends::blas::matadd(), num::backends::omp::matadd(), num::backends::seq::matadd(), Matrix(), Matrix(), operator=(), to_cpu(), and to_gpu().
to_cpu()
void num::Matrix::to_cpu ()
Definition at line 87 of file matrix.cpp.
References num::cuda::free(), size(), and num::cuda::to_host().
to_gpu()
void num::Matrix::to_gpu ()
Definition at line 80 of file matrix.cpp.
References num::cuda::alloc(), size(), and num::cuda::to_device().
The documentation for this class was generated from the following files:
/home/runner/work/numerics/numerics/include/core/matrix.hpp
/home/runner/work/numerics/numerics/src/core/matrix.cpp