numerics: physics::FluidSolver3D Class Reference
physics::FluidSolver3D Class Reference
#include <fluid3d.hpp>
Public Member Functions
FluidSolver3D (const FluidParams3D &p)
void add_particle (float x, float y, float z, float vx, float vy, float vz, float T)
void add_body (const RigidBody3D &b)
void clear ()
void step ()
Advance by one timestep. Dispatches to seq or omp backends.
const std::vector< Particle3D > & particles () const
const std::vector< RigidBody3D > & bodies () const
std::vector< RigidBody3D > & bodies ()
const FluidParams3D & params () const
FluidParams3D & params_mut ()
float min_temp () const
float max_temp () const
Detailed Description
Definition at line 45 of file fluid3d.hpp.
Constructor & Destructor Documentation
FluidSolver3D()
physics::FluidSolver3D::FluidSolver3D (const FluidParams3D & p) explicit
Definition at line 23 of file fluid3d.cpp.
Member Function Documentation
add_body()
void physics::FluidSolver3D::add_body (const RigidBody3D & b)
Definition at line 51 of file fluid3d.cpp.
add_particle()
void physics::FluidSolver3D::add_particle (float x, float y, float z, float vx, float vy, float vz, float T)
Definition at line 27 of file fluid3d.cpp.
References physics::FluidParams3D::rho0, and physics::Particle3D::x.
Referenced by Hose::emit().
bodies() [1/2]
std::vector< RigidBody3D > & physics::FluidSolver3D::bodies () inline
Definition at line 68 of file fluid3d.hpp.
bodies() [2/2]
const std::vector< RigidBody3D > & physics::FluidSolver3D::bodies () const inline
Definition at line 65 of file fluid3d.hpp.
clear()
void physics::FluidSolver3D::clear ()
Definition at line 54 of file fluid3d.cpp.
max_temp()
float physics::FluidSolver3D::max_temp () const inline
Definition at line 80 of file fluid3d.hpp.
Referenced by main().
min_temp()
float physics::FluidSolver3D::min_temp () const inline
Definition at line 77 of file fluid3d.hpp.
Referenced by main().
params()
const FluidParams3D & physics::FluidSolver3D::params () const inline
Definition at line 71 of file fluid3d.hpp.
params_mut()
FluidParams3D & physics::FluidSolver3D::params_mut () inline
Definition at line 74 of file fluid3d.hpp.
particles()
const std::vector< Particle3D > & physics::FluidSolver3D::particles () const inline
Definition at line 62 of file fluid3d.hpp.
Referenced by Hose::emit(), and main().
step()
void physics::FluidSolver3D::step ()
Advance by one timestep. Dispatches to seq or omp backends.
Definition at line 61 of file fluid3d.cpp.
References physics::FluidParams3D::alpha_T, physics::backends::omp::body_collisions(), physics::backends::seq::body_collisions(), physics::SpatialHash3D::build(), physics::backends::omp::compute_density_pressure(), physics::backends::seq::compute_density_pressure(), physics::backends::omp::compute_forces(), physics::backends::seq::compute_forces(), physics::backends::omp::enforce_boundaries(), physics::backends::seq::enforce_boundaries(), physics::FluidParams3D::h, physics::FluidParams3D::h_conv, physics::backends::omp::heat_compute(), physics::backends::seq::heat_compute(), physics::backends::omp::integrate(), physics::backends::seq::integrate(), physics::backends::seq::integrate_bodies(), physics::FluidParams3D::mass, num::omp, physics::FluidParams3D::policy, physics::backends::omp::update_temp_range(), and physics::backends::seq::update_temp_range().
The documentation for this class was generated from the following files:
/home/runner/work/numerics/numerics/apps/fluid_sim_3d/fluid3d.hpp
/home/runner/work/numerics/numerics/apps/fluid_sim_3d/fluid3d.cpp
/home/runner/work/numerics/numerics/apps/fluid_sim_3d/src/sim.cpp