numerics: /home/runner/work/numerics/numerics/apps/em_demo/main.cpp File Reference
main.cpp File Reference
Electromagnetic field demo – aluminum rod + permanent magnet.
#include "em_demo/sim.hpp"
#include "viz/viz.hpp"
#include <cmath>
#include <cstdio>
#include <chrono>
#include <vector>
Functions
template<class To , class From >
constexpr To cast (From x)
int main ()
Detailed Description
Electromagnetic field demo – aluminum rod + permanent magnet.
Physics solved once at startup (CG Poisson solvers): Electric: div(sigma * grad(phi)) = 0 -> J = sigma * (-grad phi) Magnetic: Laplacian(A) = -mu0 * J -> B = curl(A) Magnet dipole field added analytically each frame. Camera orbits the scene; ESC quits.
Definition in file main.cpp.
Function Documentation
cast()
template<class To , class From > constexpr To cast (From x) constexpr
Definition at line 20 of file main.cpp.
main()
int main ()
Definition at line 74 of file main.cpp.
References num::viz::Frame::begin3d(), num::MagneticSolver::current_density(), num::viz::Frame::end3d(), num::ScalarField3D::grid(), num::viz::heat_color(), num::viz::kGray, num::viz::kWhite, num::viz::Frame::line3d(), num::viz::Frame::rect(), num::viz::run(), num::Grid3D::set(), num::MagneticSolver::solve_magnetic_field(), physics::ElectricSolver::solve_potential(), num::viz::Frame::sphere3d(), num::viz::Frame::text(), num::viz::Frame::textf(), num::VectorField3D::x, num::VectorField3D::y, and num::VectorField3D::z.