numerics: /home/runner/work/numerics/numerics/apps/fluid_sim_3d/main.cpp File Reference
main.cpp File Reference
3D weakly-compressible SPH – dual opposing hoses.
#include "numerics.hpp"
#include "viz/viz.hpp"
#include "fluid_sim_3d/sim.hpp"
#include <cmath>
Classes
struct Hose
Functions
template<class To , class From >
constexpr To cast (From x)
int main ()
Detailed Description
3D weakly-compressible SPH – dual opposing hoses.
One cold hose and one hot hose, both always active, narrow cone (~2 deg). Particles colored by temperature (blue=cold, red=hot). SPACE pause R reset +/- substeps
Definition in file main.cpp.
Function Documentation
cast()
template<class To , class From > constexpr To cast (From x) constexpr
Definition at line 17 of file main.cpp.
main()
int main ()
Definition at line 103 of file main.cpp.
References num::viz::Frame::begin3d(), num::viz::Frame::end3d(), num::viz::heat_color(), Hose::init(), num::viz::kSkyBlue, num::viz::kWhite, physics::FluidSolver3D::max_temp(), physics::FluidSolver3D::min_temp(), physics::FluidSolver3D::particles(), num::viz::Frame::reset_pressed(), num::viz::run(), Hose::source, num::viz::Frame::sphere3d(), num::viz::Frame::step(), and num::viz::Frame::textf().