numerics: /home/runner/work/numerics/numerics/apps/fluid_sim/main.cpp File Reference
main.cpp File Reference
2D weakly-compressible SPH fluid – dam break.
#include "numerics.hpp"
#include "viz/viz.hpp"
#include "fluid_sim/sim.hpp"
#include <algorithm>
#include <cmath>
Functions
template<class To , class From >
constexpr To cast (From x)
int main ()
Detailed Description
2D weakly-compressible SPH fluid – dam break.
Left half of domain filled with water; one hot and one cold rigid body on the right. Heat diffuses between particles and bodies. SPACE pause R reset +/- substeps
Definition in file main.cpp.
Function Documentation
cast()
template<class To , class From > constexpr To cast (From x) constexpr
Definition at line 18 of file main.cpp.
main()
int main ()
Definition at line 87 of file main.cpp.
References physics::FluidSolver::bodies(), num::viz::Frame::circle(), num::viz::Frame::dot(), num::viz::heat_color(), num::viz::Frame::height, num::viz::kSkyBlue, num::viz::kWhite, physics::FluidSolver::max_temp(), physics::FluidSolver::min_temp(), physics::FluidSolver::particles(), num::viz::Frame::rect_outline(), num::viz::Frame::reset_pressed(), num::viz::run(), physics::FluidSolver::step(), num::viz::Frame::step(), num::viz::Frame::text(), num::viz::Frame::textf(), and num::viz::Frame::width.