var hierarchy =
[
    [ "num::BackwardEuler", "structnum_1_1BackwardEuler.html", null ],
    [ "num::BandedMatrix", "classnum_1_1BandedMatrix.html", null ],
    [ "num::BandedSolverResult", "structnum_1_1BandedSolverResult.html", null ],
    [ "num::BasicVector< T >", "classnum_1_1BasicVector.html", null ],
    [ "num::BasicVector< cplx >", "classnum_1_1BasicVector.html", null ],
    [ "num::BasicVector< real >", "classnum_1_1BasicVector.html", null ],
    [ "nbody::Body", "structnbody_1_1Body.html", null ],
    [ "num::viz::Frame::Cam3", "structnum_1_1viz_1_1Frame_1_1Cam3.html", null ],
    [ "num::CellList2D< Scalar >", "classnum_1_1CellList2D.html", null ],
    [ "num::CellList2D< float >", "classnum_1_1CellList2D.html", null ],
    [ "num::CellList3D< Scalar >", "classnum_1_1CellList3D.html", null ],
    [ "num::CellList3D< float >", "classnum_1_1CellList3D.html", null ],
    [ "num::Circuit", "classnum_1_1Circuit.html", null ],
    [ "num::ClusterResult", "structnum_1_1ClusterResult.html", null ],
    [ "num::viz::Color", "structnum_1_1viz_1_1Color.html", null ],
    [ "num::ComplexTriDiag", "structnum_1_1ComplexTriDiag.html", null ],
    [ "num::CrankNicolsonADI", "structnum_1_1CrankNicolsonADI.html", null ],
    [ "num::detail::CubicSigma< Dim >", "structnum_1_1detail_1_1CubicSigma.html", null ],
    [ "num::detail::CubicSigma< 2 >", "structnum_1_1detail_1_1CubicSigma_3_012_01_4.html", null ],
    [ "num::detail::CubicSigma< 3 >", "structnum_1_1detail_1_1CubicSigma_3_013_01_4.html", null ],
    [ "num::FieldSolver::DirichletBC", "structnum_1_1FieldSolver_1_1DirichletBC.html", null ],
    [ "tdse::EigenMode", "structtdse_1_1EigenMode.html", null ],
    [ "num::EigenResult", "structnum_1_1EigenResult.html", null ],
    [ "physics::ElectricSolver", "classphysics_1_1ElectricSolver.html", null ],
    [ "physics::ElectrodeBC", "structphysics_1_1ElectrodeBC.html", null ],
    [ "num::Euler", "structnum_1_1Euler.html", null ],
    [ "num::EulerSteps", "classnum_1_1EulerSteps.html", null ],
    [ "num::spectral::FFTPlan", "classnum_1_1spectral_1_1FFTPlan.html", null ],
    [ "backends::opt::FFTPlanImpl", "structbackends_1_1opt_1_1FFTPlanImpl.html", null ],
    [ "backends::seq::FFTPlanImpl", "structbackends_1_1seq_1_1FFTPlanImpl.html", null ],
    [ "num::viz::detail::FieldCanvas", "structnum_1_1viz_1_1detail_1_1FieldCanvas.html", null ],
    [ "num::FieldSolver", "classnum_1_1FieldSolver.html", null ],
    [ "physics::FluidParams", "structphysics_1_1FluidParams.html", null ],
    [ "physics::FluidParams3D", "structphysics_1_1FluidParams3D.html", null ],
    [ "physics::FluidSolver", "classphysics_1_1FluidSolver.html", null ],
    [ "physics::FluidSolver3D", "classphysics_1_1FluidSolver3D.html", null ],
    [ "num::viz::Frame", "structnum_1_1viz_1_1Frame.html", null ],
    [ "num::GateView", "structnum_1_1GateView.html", null ],
    [ "num::GivensRotation", "structnum_1_1GivensRotation.html", null ],
    [ "num::Gnuplot", "classnum_1_1Gnuplot.html", null ],
    [ "num::Grid2D", "structnum_1_1Grid2D.html", null ],
    [ "num::Grid3D", "classnum_1_1Grid3D.html", null ],
    [ "physics::HeatParams", "structphysics_1_1HeatParams.html", null ],
    [ "physics::HeatParams3D", "structphysics_1_1HeatParams3D.html", null ],
    [ "num::Histogram", "structnum_1_1Histogram.html", null ],
    [ "Hose", "structHose.html", null ],
    [ "num::ode::ImplicitParams", "structnum_1_1ode_1_1ImplicitParams.html", null ],
    [ "num::IntRange", "structnum_1_1IntRange.html", null ],
    [ "IsingLattice< N >", "structIsingLattice.html", null ],
    [ "num::EulerSteps::iterator", "structnum_1_1EulerSteps_1_1iterator.html", null ],
    [ "num::RK45Steps::iterator", "structnum_1_1RK45Steps_1_1iterator.html", null ],
    [ "num::RK4_2ndSteps::iterator", "structnum_1_1RK4__2ndSteps_1_1iterator.html", null ],
    [ "num::RK4Steps::iterator", "structnum_1_1RK4Steps_1_1iterator.html", null ],
    [ "num::VerletSteps::iterator", "structnum_1_1VerletSteps_1_1iterator.html", null ],
    [ "num::Yoshida4Steps::iterator", "structnum_1_1Yoshida4Steps_1_1iterator.html", null ],
    [ "num::LanczosResult", "structnum_1_1LanczosResult.html", null ],
    [ "num::LUResult", "structnum_1_1LUResult.html", null ],
    [ "num::MagneticSolver", "classnum_1_1MagneticSolver.html", null ],
    [ "num::Matrix", "classnum_1_1Matrix.html", null ],
    [ "num::MCMCProblem", "structnum_1_1MCMCProblem.html", null ],
    [ "num::Metropolis", "structnum_1_1Metropolis.html", null ],
    [ "num::markov::MetropolisStats", "structnum_1_1markov_1_1MetropolisStats.html", null ],
    [ "nbody::NBodySim", "structnbody_1_1NBodySim.html", null ],
    [ "ns::NSSolver", "classns_1_1NSSolver.html", null ],
    [ "num::ODEParams", "structnum_1_1ODEParams.html", null ],
    [ "num::ODEProblem", "structnum_1_1ODEProblem.html", null ],
    [ "num::ODEResult", "structnum_1_1ODEResult.html", null ],
    [ "physics::Particle", "structphysics_1_1Particle.html", null ],
    [ "physics::Particle3D", "structphysics_1_1Particle3D.html", null ],
    [ "num::PBCLattice2D", "structnum_1_1PBCLattice2D.html", null ],
    [ "num::PowerResult", "structnum_1_1PowerResult.html", null ],
    [ "Preset", "structPreset.html", null ],
    [ "num::QRResult", "structnum_1_1QRResult.html", null ],
    [ "num::Result", "structnum_1_1Result.html", null ],
    [ "physics::RigidBody", "structphysics_1_1RigidBody.html", null ],
    [ "physics::RigidBody3D", "structphysics_1_1RigidBody3D.html", null ],
    [ "num::RK4", "structnum_1_1RK4.html", null ],
    [ "num::RK45", "structnum_1_1RK45.html", null ],
    [ "num::RK45Steps", "classnum_1_1RK45Steps.html", null ],
    [ "num::RK4_2ndSteps", "classnum_1_1RK4__2ndSteps.html", null ],
    [ "num::RK4Steps", "classnum_1_1RK4Steps.html", null ],
    [ "num::Rng", "structnum_1_1Rng.html", null ],
    [ "num::RootResult", "structnum_1_1RootResult.html", null ],
    [ "num::RunningStats", "structnum_1_1RunningStats.html", null ],
    [ "num::ScalarField2D", "classnum_1_1ScalarField2D.html", null ],
    [ "num::ScalarField3D", "classnum_1_1ScalarField3D.html", null ],
    [ "num::SmallMatrix< M, N >", "structnum_1_1SmallMatrix.html", null ],
    [ "num::SmallVec< N >", "structnum_1_1SmallVec.html", null ],
    [ "num::SolverResult", "structnum_1_1SolverResult.html", null ],
    [ "num::SparseMatrix", "classnum_1_1SparseMatrix.html", null ],
    [ "physics::SpatialHash", "classphysics_1_1SpatialHash.html", null ],
    [ "physics::SpatialHash3D", "classphysics_1_1SpatialHash3D.html", null ],
    [ "num::SPHKernel< Dim >", "structnum_1_1SPHKernel.html", null ],
    [ "num::detail::SpikyDW< Dim >", "structnum_1_1detail_1_1SpikyDW.html", null ],
    [ "num::detail::SpikyDW< 2 >", "structnum_1_1detail_1_1SpikyDW_3_012_01_4.html", null ],
    [ "num::detail::SpikyDW< 3 >", "structnum_1_1detail_1_1SpikyDW_3_013_01_4.html", null ],
    [ "num::viz::detail::State", "structnum_1_1viz_1_1detail_1_1State.html", null ],
    [ "ns::Stats", "structns_1_1Stats.html", null ],
    [ "tdse::Stats", "structtdse_1_1Stats.html", null ],
    [ "num::Step", "structnum_1_1Step.html", null ],
    [ "num::StepEnd", "structnum_1_1StepEnd.html", null ],
    [ "num::SVDResult", "structnum_1_1SVDResult.html", null ],
    [ "num::SymplecticResult", "structnum_1_1SymplecticResult.html", null ],
    [ "num::SymplecticStep", "structnum_1_1SymplecticStep.html", null ],
    [ "tdse::TDSESolver", "classtdse_1_1TDSESolver.html", null ],
    [ "Tracer", "structTracer.html", null ],
    [ "num::markov::UmbrellaStats", "structnum_1_1markov_1_1UmbrellaStats.html", null ],
    [ "num::markov::UmbrellaWindow", "structnum_1_1markov_1_1UmbrellaWindow.html", null ],
    [ "V2", "structV2.html", null ],
    [ "num::Vec2ConstView", "structnum_1_1Vec2ConstView.html", null ],
    [ "num::Vec2View", "structnum_1_1Vec2View.html", null ],
    [ "std::vector", null, [
      [ "num::Series", "structnum_1_1Series.html", null ]
    ] ],
    [ "num::VectorField3D", "structnum_1_1VectorField3D.html", null ],
    [ "num::VerletList2D< Scalar >", "classnum_1_1VerletList2D.html", null ],
    [ "num::VerletSteps", "classnum_1_1VerletSteps.html", null ],
    [ "num::Yoshida4Steps", "classnum_1_1Yoshida4Steps.html", null ]
];