numerics: physics::backends::omp Namespace Reference
physics::backends::omp Namespace Reference
Functions
void compute_density_pressure (std::vector< Particle > &particles, const FluidParams &params, const SpatialHash &grid)
Per-particle query – each thread writes only to particles[i]. O(n*k).
void compute_forces (std::vector< Particle > &particles, const FluidParams &params, const SpatialHash &grid)
Per-particle query – each thread writes only to particles[i]. O(n*k).
void body_collisions (std::vector< Particle > &particles, const std::vector< RigidBody > &bodies, const FluidParams &params)
void integrate (std::vector< Particle > &particles, const FluidParams &params)
void enforce_boundaries (std::vector< Particle > &particles, const FluidParams &params)
void update_temp_range (const std::vector< Particle > &particles, const std::vector< RigidBody > &bodies, float &T_min, float &T_max)
reduction(min:T_min) reduction(max:T_max)
void heat_compute (std::vector< Particle > &particles, const std::vector< RigidBody > &bodies, const SpatialHash &grid, const HeatParams &params)
void compute_density_pressure (std::vector< Particle3D > &particles, const FluidParams3D &params, const SpatialHash3D &grid)
void compute_forces (std::vector< Particle3D > &particles, const FluidParams3D &params, const SpatialHash3D &grid)
void body_collisions (std::vector< Particle3D > &particles, const std::vector< RigidBody3D > &bodies, const FluidParams3D &params)
void integrate (std::vector< Particle3D > &particles, const FluidParams3D &params)
void enforce_boundaries (std::vector< Particle3D > &particles, const FluidParams3D &params)
void update_temp_range (const std::vector< Particle3D > &particles, const std::vector< RigidBody3D > &bodies, float &T_min, float &T_max)
void heat_compute (std::vector< Particle3D > &particles, const std::vector< RigidBody3D > &bodies, const SpatialHash3D &grid, const HeatParams3D &params)
Function Documentation
body_collisions() [1/2]
void physics::backends::omp::body_collisions (std::vector< Particle > & particles, const std::vector< RigidBody > & bodies, const FluidParams & params)
Definition at line 112 of file fluid.cpp.
References physics::backends::seq::body_collisions(), physics::FluidParams::restitution, physics::Particle::vx, physics::Particle::vy, physics::Particle::x, and physics::Particle::y.
Referenced by physics::FluidSolver::step(), and physics::FluidSolver3D::step().
body_collisions() [2/2]
void physics::backends::omp::body_collisions (std::vector< Particle3D > & particles, const std::vector< RigidBody3D > & bodies, const FluidParams3D & params)
Definition at line 113 of file fluid.cpp.
References physics::backends::seq::body_collisions(), physics::FluidParams3D::restitution, physics::Particle3D::vx, physics::Particle3D::vy, physics::Particle3D::vz, physics::Particle3D::x, physics::Particle3D::y, and physics::Particle3D::z.
compute_density_pressure() [1/2]
void physics::backends::omp::compute_density_pressure (std::vector< Particle > & particles, const FluidParams & params, const SpatialHash & grid)
Per-particle query – each thread writes only to particles[i]. O(n*k).
Definition at line 36 of file fluid.cpp.
References physics::FluidParams::c0, physics::backends::seq::compute_density_pressure(), physics::FluidParams::gamma, physics::FluidParams::h, physics::FluidParams::mass, num::pi, physics::SpatialHash::query(), physics::FluidParams::rho0, and num::SPHKernel< Dim >::W().
Referenced by physics::FluidSolver::step(), and physics::FluidSolver3D::step().
compute_density_pressure() [2/2]
void physics::backends::omp::compute_density_pressure (std::vector< Particle3D > & particles, const FluidParams3D & params, const SpatialHash3D & grid)
Definition at line 33 of file fluid.cpp.
References physics::FluidParams3D::c0, physics::backends::seq::compute_density_pressure(), physics::FluidParams3D::gamma, physics::FluidParams3D::h, physics::FluidParams3D::mass, physics::SpatialHash3D::query(), physics::FluidParams3D::rho0, and num::SPHKernel< Dim >::W().
compute_forces() [1/2]
void physics::backends::omp::compute_forces (std::vector< Particle > & particles, const FluidParams & params, const SpatialHash & grid)
Per-particle query – each thread writes only to particles[i]. O(n*k).
Definition at line 68 of file fluid.cpp.
References physics::backends::seq::compute_forces(), physics::Particle::density, physics::Particle::evx, physics::Particle::evy, physics::FluidParams::gx, physics::FluidParams::gy, physics::FluidParams::h, physics::FluidParams::mass, physics::FluidParams::mu, num::pi, physics::Particle::pressure, physics::SpatialHash::query(), num::SPHKernel< Dim >::Spiky_dW_dr(), num::SPHKernel< Dim >::Spiky_gradW(), physics::Particle::x, and physics::Particle::y.
Referenced by physics::FluidSolver::step(), and physics::FluidSolver3D::step().
compute_forces() [2/2]
void physics::backends::omp::compute_forces (std::vector< Particle3D > & particles, const FluidParams3D & params, const SpatialHash3D & grid)
Definition at line 66 of file fluid.cpp.
References physics::backends::seq::compute_forces(), physics::Particle3D::density, physics::Particle3D::evx, physics::Particle3D::evy, physics::Particle3D::evz, physics::FluidParams3D::gx, physics::FluidParams3D::gy, physics::FluidParams3D::gz, physics::FluidParams3D::h, physics::FluidParams3D::mass, physics::FluidParams3D::mu, physics::Particle3D::pressure, physics::SpatialHash3D::query(), num::SPHKernel< Dim >::Spiky_dW_dr(), num::SPHKernel< Dim >::Spiky_gradW(), physics::Particle3D::x, physics::Particle3D::y, and physics::Particle3D::z.
enforce_boundaries() [1/2]
void physics::backends::omp::enforce_boundaries (std::vector< Particle > & particles, const FluidParams & params)
Definition at line 161 of file fluid.cpp.
References num::e, physics::backends::seq::enforce_boundaries(), physics::FluidParams::restitution, physics::Particle::vx, physics::Particle::vy, physics::Particle::x, physics::FluidParams::xmax, physics::FluidParams::xmin, physics::Particle::y, physics::FluidParams::ymax, and physics::FluidParams::ymin.
Referenced by physics::FluidSolver::step(), and physics::FluidSolver3D::step().
enforce_boundaries() [2/2]
void physics::backends::omp::enforce_boundaries (std::vector< Particle3D > & particles, const FluidParams3D & params)
Definition at line 169 of file fluid.cpp.
References physics::backends::seq::enforce_boundaries(), physics::FluidParams3D::restitution, physics::Particle3D::vx, physics::Particle3D::vy, physics::Particle3D::vz, physics::Particle3D::x, physics::FluidParams3D::xmax, physics::FluidParams3D::xmin, physics::Particle3D::y, physics::FluidParams3D::ymax, physics::FluidParams3D::ymin, physics::Particle3D::z, physics::FluidParams3D::zmax, and physics::FluidParams3D::zmin.
heat_compute() [1/2]
void physics::backends::omp::heat_compute (std::vector< Particle > & particles, const std::vector< RigidBody > & bodies, const SpatialHash & grid, const HeatParams & params)
Definition at line 18 of file heat.cpp.
References physics::HeatParams::alpha_T, physics::Particle::density, num::SPHKernel< Dim >::dW_dr(), physics::HeatParams::h, physics::HeatParams::h_conv, physics::backends::seq::heat_compute(), physics::HeatParams::mass, physics::SpatialHash::query(), physics::Particle::temperature, physics::Particle::x, and physics::Particle::y.
Referenced by physics::FluidSolver::step(), and physics::FluidSolver3D::step().
heat_compute() [2/2]
void physics::backends::omp::heat_compute (std::vector< Particle3D > & particles, const std::vector< RigidBody3D > & bodies, const SpatialHash3D & grid, const HeatParams3D & params)
Definition at line 18 of file heat.cpp.
References physics::HeatParams3D::alpha_T, physics::Particle3D::density, num::SPHKernel< Dim >::dW_dr(), physics::HeatParams3D::h, physics::HeatParams3D::h_conv, physics::backends::seq::heat_compute(), physics::HeatParams3D::mass, physics::SpatialHash3D::query(), physics::Particle3D::temperature, physics::Particle3D::x, physics::Particle3D::y, and physics::Particle3D::z.
integrate() [1/2]
void physics::backends::omp::integrate (std::vector< Particle > & particles, const FluidParams & params)
Definition at line 140 of file fluid.cpp.
References physics::Particle::ax, physics::Particle::ay, physics::FluidParams::dt, physics::Particle::dT_dt, physics::Particle::evx, physics::Particle::evy, physics::backends::seq::integrate(), physics::Particle::temperature, physics::Particle::vx, physics::Particle::vy, physics::Particle::x, and physics::Particle::y.
Referenced by physics::FluidSolver::step(), and physics::FluidSolver3D::step().
integrate() [2/2]
void physics::backends::omp::integrate (std::vector< Particle3D > & particles, const FluidParams3D & params)
Definition at line 144 of file fluid.cpp.
References physics::Particle3D::ax, physics::Particle3D::ay, physics::Particle3D::az, physics::FluidParams3D::dt, physics::Particle3D::dT_dt, physics::Particle3D::evx, physics::Particle3D::evy, physics::Particle3D::evz, physics::backends::seq::integrate(), physics::Particle3D::temperature, physics::Particle3D::vx, physics::Particle3D::vy, physics::Particle3D::vz, physics::Particle3D::x, physics::Particle3D::y, and physics::Particle3D::z.
update_temp_range() [1/2]
void physics::backends::omp::update_temp_range (const std::vector< Particle > & particles, const std::vector< RigidBody > & bodies, float & T_min, float & T_max)
reduction(min:T_min) reduction(max:T_max)
Definition at line 191 of file fluid.cpp.
References physics::backends::seq::update_temp_range().
Referenced by physics::FluidSolver::step(), and physics::FluidSolver3D::step().
update_temp_range() [2/2]
void physics::backends::omp::update_temp_range (const std::vector< Particle3D > & particles, const std::vector< RigidBody3D > & bodies, float & T_min, float & T_max)
Definition at line 207 of file fluid.cpp.
References physics::backends::seq::update_temp_range().