numerics: num::backends::seq Namespace Reference
num::backends::seq Namespace Reference
Functions
void scale (Vector &v, real alpha)
void add (const Vector &x, const Vector &y, Vector &z)
void axpy (real alpha, const Vector &x, Vector &y)
real dot (const Vector &x, const Vector &y)
real norm (const Vector &x)
void matmul (const Matrix &A, const Matrix &B, Matrix &C)
void matmul_blocked (const Matrix &A, const Matrix &B, Matrix &C, idx block_size)
void matmul_register_blocked (const Matrix &A, const Matrix &B, Matrix &C, idx block_size, idx reg_size)
void matvec (const Matrix &A, const Vector &x, Vector &y)
void matadd (real alpha, const Matrix &A, real beta, const Matrix &B, Matrix &C)
EigenResult eig_sym (const Matrix &A, real tol, idx max_sweeps)
LUResult lu (const Matrix &A)
QRResult qr (const Matrix &A)
void thomas (const Vector &a, const Vector &b, const Vector &c, const Vector &d, Vector &x)
SVDResult svd (const Matrix &A, real tol, idx max_sweeps)
Function Documentation
add()
void num::backends::seq::add (const Vector & x, const Vector & y, Vector & z)
Definition at line 14 of file vector.cpp.
References num::BasicVector< T >::size().
Referenced by num::add().
axpy()
void num::backends::seq::axpy (real alpha, const Vector & x, Vector & y)
Definition at line 19 of file vector.cpp.
References num::BasicVector< T >::size().
Referenced by num::backends::blas::axpy(), num::backends::gpu::axpy(), num::backends::omp::axpy(), and num::axpy().
dot()
real num::backends::seq::dot (const Vector & x, const Vector & y)
Definition at line 24 of file vector.cpp.
References num::BasicVector< T >::size().
Referenced by num::backends::blas::dot(), num::backends::gpu::dot(), num::backends::omp::dot(), and num::dot().
eig_sym()
EigenResult num::backends::seq::eig_sym (const Matrix & A, real tol, idx max_sweeps)
Definition at line 19 of file jacobi_eig.cpp.
References num::Matrix::cols(), num::e, and num::Matrix::rows().
Referenced by num::backends::lapack::eig_sym(), and num::eig_sym().
lu()
LUResult num::backends::seq::lu (const Matrix & A)
Definition at line 9 of file lu.cpp.
References num::e, num::LUResult::LU, num::LUResult::piv, num::Matrix::rows(), and num::LUResult::singular.
Referenced by num::backends::lapack::lu(), and num::lu().
matadd()
void num::backends::seq::matadd (real alpha, const Matrix & A, real beta, const Matrix & B, Matrix & C)
Definition at line 32 of file matrix.cpp.
References num::beta(), num::Matrix::data(), and num::Matrix::size().
Referenced by num::backends::blas::matadd(), num::backends::omp::matadd(), and num::matadd().
matmul()
void num::backends::seq::matmul (const Matrix & A, const Matrix & B, Matrix & C)
Definition at line 14 of file matrix.cpp.
References num::Matrix::cols(), and num::Matrix::rows().
Referenced by num::backends::gpu::matmul(), num::backends::omp::matmul(), and num::matmul().
matmul_blocked()
void num::backends::seq::matmul_blocked (const Matrix & A, const Matrix & B, Matrix & C, idx block_size)
Definition at line 77 of file matrix.cpp.
References num::Matrix::cols(), num::Matrix::data(), and num::Matrix::rows().
Referenced by num::backends::blas::matmul(), num::matmul(), num::backends::simd::matmul(), and num::matmul_blocked().
matmul_register_blocked()
void num::backends::seq::matmul_register_blocked (const Matrix & A, const Matrix & B, Matrix & C, idx block_size, idx reg_size)
Definition at line 114 of file matrix.cpp.
References num::Matrix::cols(), num::Matrix::data(), and num::Matrix::rows().
Referenced by num::matmul_register_blocked().
matvec()
void num::backends::seq::matvec (const Matrix & A, const Vector & x, Vector & y)
Definition at line 24 of file matrix.cpp.
References num::Matrix::cols(), and num::Matrix::rows().
Referenced by num::backends::blas::matvec(), num::backends::gpu::matvec(), num::backends::omp::matvec(), num::backends::simd::matvec(), and num::matvec().
norm()
real num::backends::seq::norm (const Vector & x)
Definition at line 31 of file vector.cpp.
References num::BasicVector< T >::size().
Referenced by num::backends::blas::norm(), num::backends::gpu::norm(), and num::norm().
qr()
QRResult num::backends::seq::qr (const Matrix & A)
Definition at line 11 of file qr.cpp.
References num::Matrix::cols(), num::e, and num::Matrix::rows().
Referenced by num::backends::lapack::qr(), and num::qr().
scale()
void num::backends::seq::scale (Vector & v, real alpha)
Definition at line 9 of file vector.cpp.
References num::BasicVector< T >::size().
Referenced by num::backends::blas::scale(), num::backends::gpu::scale(), num::backends::omp::scale(), and num::scale().
svd()
SVDResult num::backends::seq::svd (const Matrix & A, real tol, idx max_sweeps)
Definition at line 11 of file svd.cpp.
References num::beta(), num::Matrix::cols(), num::e, num::Matrix::rows(), and num::zeta().
Referenced by num::backends::lapack::svd(), and num::svd().
thomas()
void num::backends::seq::thomas (const Vector & a, const Vector & b, const Vector & c, const Vector & d, Vector & x)
Definition at line 8 of file thomas.cpp.
References num::BasicVector< T >::size().
Referenced by num::backends::lapack::thomas(), and num::thomas().