numerics: num::backends::omp Namespace Reference
num::backends::omp Namespace Reference
Functions
void scale (Vector &v, real alpha)
void axpy (real alpha, const Vector &x, Vector &y)
real dot (const Vector &x, const Vector &y)
void matmul (const Matrix &A, const Matrix &B, Matrix &C)
void matvec (const Matrix &A, const Vector &x, Vector &y)
void matadd (real alpha, const Matrix &A, real beta, const Matrix &B, Matrix &C)
EigenResult eig_sym (const Matrix &A, real tol, idx max_sweeps)
Function Documentation
axpy()
void num::backends::omp::axpy (real alpha, const Vector & x, Vector & y)
Definition at line 20 of file vector.cpp.
References num::backends::seq::axpy(), and num::BasicVector< T >::size().
Referenced by num::axpy().
dot()
real num::backends::omp::dot (const Vector & x, const Vector & y)
Definition at line 31 of file vector.cpp.
References num::backends::seq::dot(), and num::BasicVector< T >::size().
Referenced by num::dot().
eig_sym()
EigenResult num::backends::omp::eig_sym (const Matrix & A, real tol, idx max_sweeps)
Definition at line 17 of file jacobi_eig.cpp.
References num::Matrix::cols(), num::e, and num::Matrix::rows().
Referenced by num::eig_sym().
matadd()
void num::backends::omp::matadd (real alpha, const Matrix & A, real beta, const Matrix & B, Matrix & C)
Definition at line 56 of file matrix.cpp.
References num::beta(), num::Matrix::data(), num::backends::seq::matadd(), and num::Matrix::size().
Referenced by num::matadd().
matmul()
void num::backends::omp::matmul (const Matrix & A, const Matrix & B, Matrix & C)
Definition at line 14 of file matrix.cpp.
References num::Matrix::cols(), num::Matrix::data(), num::backends::seq::matmul(), and num::Matrix::rows().
Referenced by num::matmul().
matvec()
void num::backends::omp::matvec (const Matrix & A, const Vector & x, Vector & y)
Definition at line 42 of file matrix.cpp.
References num::Matrix::cols(), num::backends::seq::matvec(), and num::Matrix::rows().
Referenced by num::matvec().
scale()
void num::backends::omp::scale (Vector & v, real alpha)
Definition at line 9 of file vector.cpp.
References num::backends::seq::scale(), and num::BasicVector< T >::size().
Referenced by num::scale().