numerics: backends::seq Namespace Reference
backends::seq Namespace Reference
Classes
struct FFTPlanImpl
Functions
void bit_reverse (num::CVector &a)
void cooley_tukey (num::CVector &a, bool invert)
void fft (const num::CVector &in, num::CVector &out)
void ifft (const num::CVector &in, num::CVector &out)
void rfft (const num::Vector &in, num::CVector &out)
void irfft (const num::CVector &in, int n, num::Vector &out)
Function Documentation
bit_reverse()
void backends::seq::bit_reverse (num::CVector & a) inline
Definition at line 15 of file impl.hpp.
References num::BasicVector< T >::size().
Referenced by cooley_tukey(), backends::opt::FFTPlanImpl::execute(), and backends::seq::FFTPlanImpl::execute().
cooley_tukey()
void backends::seq::cooley_tukey (num::CVector & a, bool invert) inline
Definition at line 27 of file impl.hpp.
References bit_reverse(), and num::BasicVector< T >::size().
Referenced by fft(), ifft(), irfft(), and rfft().
fft()
void backends::seq::fft (const num::CVector & in, num::CVector & out) inline
Definition at line 48 of file impl.hpp.
References cooley_tukey(), and num::BasicVector< T >::size().
Referenced by num::spectral::fft().
ifft()
void backends::seq::ifft (const num::CVector & in, num::CVector & out) inline
Definition at line 54 of file impl.hpp.
References cooley_tukey(), and num::BasicVector< T >::size().
Referenced by num::spectral::ifft().
irfft()
void backends::seq::irfft (const num::CVector & in, int n, num::Vector & out) inline
Definition at line 70 of file impl.hpp.
References cooley_tukey().
Referenced by num::spectral::irfft().
rfft()
void backends::seq::rfft (const num::Vector & in, num::CVector & out) inline
Definition at line 60 of file impl.hpp.
References cooley_tukey(), and num::BasicVector< T >::size().
Referenced by num::spectral::rfft().