numerics: num::backends::lapack Namespace Reference
num::backends::lapack Namespace Reference
Functions
EigenResult eig_sym (const Matrix &A)
LUResult lu (const Matrix &A)
QRResult qr (const Matrix &A)
void thomas (const Vector &a, const Vector &b, const Vector &c, const Vector &d, Vector &x)
SVDResult svd (const Matrix &A)
Function Documentation
eig_sym()
EigenResult num::backends::lapack::eig_sym (const Matrix & A)
Definition at line 14 of file jacobi_eig.cpp.
References num::Matrix::cols(), num::Matrix::data(), num::BasicVector< T >::data(), num::e, num::backends::seq::eig_sym(), and num::Matrix::rows().
Referenced by num::eig_sym().
lu()
LUResult num::backends::lapack::lu (const Matrix & A)
Definition at line 18 of file lu.cpp.
References num::Matrix::data(), num::LUResult::LU, num::backends::seq::lu(), num::LUResult::piv, num::Matrix::rows(), and num::LUResult::singular.
Referenced by num::lu().
qr()
QRResult num::backends::lapack::qr (const Matrix & A)
Definition at line 16 of file qr.cpp.
References num::Matrix::cols(), num::Matrix::data(), num::backends::seq::qr(), and num::Matrix::rows().
Referenced by num::qr().
svd()
SVDResult num::backends::lapack::svd (const Matrix & A)
Definition at line 15 of file svd.cpp.
References num::Matrix::cols(), num::Matrix::data(), num::BasicVector< T >::data(), num::e, num::Matrix::rows(), and num::backends::seq::svd().
Referenced by num::svd().
thomas()
void num::backends::lapack::thomas (const Vector & a, const Vector & b, const Vector & c, const Vector & d, Vector & x)
Definition at line 15 of file thomas.cpp.
References num::BasicVector< T >::data(), num::BasicVector< T >::size(), and num::backends::seq::thomas().
Referenced by num::thomas().