numerics: num::detail Namespace Reference
num::detail Namespace Reference
Classes
struct CubicSigma
struct CubicSigma< 2 >
struct CubicSigma< 3 >
struct SpikyDW
struct SpikyDW< 2 >
struct SpikyDW< 3 >
Functions
real normalise (Vector &v)
Normalise v in-place; returns the old norm.
Function Documentation
normalise()
real num::detail::normalise (Vector & v) inline
Normalise v in-place; returns the old norm.
Definition at line 34 of file power.hpp.
References num::e, and num::BasicVector< T >::size().
Referenced by num::inverse_iteration(), num::power_iteration(), and num::rayleigh_iteration().