numerics: num::quantum Namespace Reference
num::quantum Namespace Reference
Typedefs
using Statevector = num::CVector
Dense statevector: complex vector of length 2^n_qubits, backed by num::CVector.
using Gate = std::array< cplx, 4 >
2x2 single-qubit gate stored row-major: { G[0,0], G[0,1], G[1,0], G[1,1] }
using Gate2Q = std::array< cplx, 16 >
4x4 two-qubit gate stored row-major (16 entries)
using cplx = std::complex< real >
Functions
Statevector zero_state (int n_qubits)
Returns |0...0> computational basis state for n_qubits qubits.
Statevector basis_state (int n_qubits, int k)
Returns the computational basis state |k> for an n_qubits system.
Gate gate_x ()
Pauli-X (NOT)
Gate gate_y ()
Pauli-Y.
Gate gate_z ()
Pauli-Z.
Gate gate_h ()
Hadamard.
Gate gate_s ()
Phase gate S = diag(1, i)
Gate gate_sdg ()
Sdg = diag(1, -i)
Gate gate_t ()
T gate = diag(1, e^{ipi/4})
Gate gate_tdg ()
Tdg gate.
Gate gate_rx (real theta)
Rotation about X: R_x(theta) = exp(-ithetaX/2)
Gate gate_ry (real theta)
Rotation about Y: R_y(theta) = exp(-ithetaY/2)
Gate gate_rz (real theta)
Rotation about Z: R_z(theta) = exp(-ithetaZ/2)
Gate gate_p (real lambda)
Phase gate: diag(1, e^{ilambda})
Gate gate_u (real theta, real phi, real lambda)
General SU(2) gate.
Gate2Q gate2q_cnot ()
CNOT (qubit 0 = control, qubit 1 = target in subspace)
Gate2Q gate2q_cz ()
Controlled-Z.
Gate2Q gate2q_swap ()
SWAP.
void apply_1q (Statevector &sv, int n_qubits, const Gate &G, int target)
Apply a 2x2 gate to a single qubit in-place.
void apply_2q (Statevector &sv, int n_qubits, const Gate2Q &G, int q0, int q1)
Apply a general 4x4 two-qubit gate to qubits q0, q1.
void apply_cnot (Statevector &sv, int n_qubits, int control, int target)
CNOT with explicit control and target qubits.
void apply_cz (Statevector &sv, int n_qubits, int control, int target)
Controlled-Z.
void apply_swap (Statevector &sv, int n_qubits, int q0, int q1)
SWAP two qubits.
void apply_toffoli (Statevector &sv, int n_qubits, int c0, int c1, int target)
Toffoli (CCX) gate.
void apply_cy (Statevector &sv, int n_qubits, int control, int target)
Controlled-Y.
void apply_cp (Statevector &sv, int n_qubits, real lambda, int control, int target)
Controlled phase: applies phase e^{ilambda} when both control=1 and target=1.
void apply_cswap (Statevector &sv, int n_qubits, int ctrl, int q0, int q1)
Fredkin (CSWAP): swaps q0 and q1 when ctrl=1.
real norm (const Statevector &sv)
L2 norm of the statevector (should be 1 for a valid quantum state)
void normalize (Statevector &sv)
Normalize statevector in-place.
std::vector< real > probabilities (const Statevector &sv)
Measurement probability for each basis state: p_i = |a_i|^2.
real expectation (const Statevector &sv, std::function< void(const Statevector &, Statevector &)> op)
Expectation value <psi|O|psi> for a Hermitian operator given as matrix-free matvec.
real expectation_z (const Statevector &sv, int qubit)
<Z_q> = P(q=0) - P(q=1) for qubit q
real expectation_x (const Statevector &sv, int n_qubits, int qubit)
<X_q> for qubit q
real expectation_y (const Statevector &sv, int n_qubits, int qubit)
<Y_q> for qubit q
std::array< std::complex< real >, 4 > reduced_density_matrix (const Statevector &sv, int n_qubits, int qubit)
Reduced density matrix for a single qubit (2x2, returned row-major)
real entanglement_entropy (const Statevector &sv, int n_qubits, int qubit)
Von Neumann entropy of a single qubit's reduced density matrix.
Typedef Documentation
cplx
using num::quantum::cplx = typedef std::complex<real>
Definition at line 7 of file statevector.cpp.
Gate
using num::quantum::Gate = typedef std::array<cplx, 4>
2x2 single-qubit gate stored row-major: { G[0,0], G[0,1], G[1,0], G[1,1] }
Definition at line 33 of file statevector.hpp.
Gate2Q
using num::quantum::Gate2Q = typedef std::array<cplx, 16>
4x4 two-qubit gate stored row-major (16 entries)
Definition at line 36 of file statevector.hpp.
Statevector
using num::quantum::Statevector = typedef num::CVector
Dense statevector: complex vector of length 2^n_qubits, backed by num::CVector.
Definition at line 29 of file statevector.hpp.
Function Documentation
apply_1q()
void num::quantum::apply_1q (Statevector & sv, int n_qubits, const Gate & G, int target)
Apply a 2x2 gate to a single qubit in-place.
Parameters
sv Statevector of length 2^n_qubits (modified in-place)
n_qubits Total number of qubits
G 2x2 gate (row-major)
target Target qubit index (0 = LSB)
Definition at line 117 of file statevector.cpp.
Referenced by expectation_x(), and expectation_y().
apply_2q()
void num::quantum::apply_2q (Statevector & sv, int n_qubits, const Gate2Q & G, int q0, int q1)
Apply a general 4x4 two-qubit gate to qubits q0, q1.
Parameters
sv Statevector
n_qubits Total number of qubits
G 4x4 gate acting on (q0, q1) in little-endian order
q0 First qubit (LSB of the 2-qubit subspace)
q1 Second qubit (MSB of the 2-qubit subspace)
Definition at line 132 of file statevector.cpp.
apply_cnot()
void num::quantum::apply_cnot (Statevector & sv, int n_qubits, int control, int target)
CNOT with explicit control and target qubits.
Definition at line 149 of file statevector.cpp.
apply_cp()
void num::quantum::apply_cp (Statevector & sv, int n_qubits, real lambda, int control, int target)
Controlled phase: applies phase e^{ilambda} when both control=1 and target=1.
Definition at line 294 of file statevector.cpp.
apply_cswap()
void num::quantum::apply_cswap (Statevector & sv, int n_qubits, int ctrl, int q0, int q1)
Fredkin (CSWAP): swaps q0 and q1 when ctrl=1.
Definition at line 309 of file statevector.cpp.
apply_cy()
void num::quantum::apply_cy (Statevector & sv, int n_qubits, int control, int target)
Controlled-Y.
Definition at line 279 of file statevector.cpp.
apply_cz()
void num::quantum::apply_cz (Statevector & sv, int n_qubits, int control, int target)
Controlled-Z.
Definition at line 158 of file statevector.cpp.
apply_swap()
void num::quantum::apply_swap (Statevector & sv, int n_qubits, int q0, int q1)
SWAP two qubits.
Definition at line 167 of file statevector.cpp.
apply_toffoli()
void num::quantum::apply_toffoli (Statevector & sv, int n_qubits, int c0, int c1, int target)
Toffoli (CCX) gate.
Definition at line 176 of file statevector.cpp.
basis_state()
Statevector num::quantum::basis_state (int n_qubits, int k)
Returns the computational basis state |k> for an n_qubits system.
Definition at line 18 of file statevector.cpp.
entanglement_entropy()
real num::quantum::entanglement_entropy (const Statevector & sv, int n_qubits, int qubit)
Von Neumann entropy of a single qubit's reduced density matrix.
Definition at line 265 of file statevector.cpp.
References num::e, and reduced_density_matrix().
Referenced by main().
expectation()
real num::quantum::expectation (const Statevector & sv, std::function< void(const Statevector &, Statevector &)> op)
Expectation value <psi|O|psi> for a Hermitian operator given as matrix-free matvec.
Definition at line 204 of file statevector.cpp.
References num::BasicVector< T >::size().
expectation_x()
real num::quantum::expectation_x (const Statevector & sv, int n_qubits, int qubit)
<X_q> for qubit q
Definition at line 224 of file statevector.cpp.
References apply_1q(), gate_x(), and num::BasicVector< T >::size().
expectation_y()
real num::quantum::expectation_y (const Statevector & sv, int n_qubits, int qubit)
<Y_q> for qubit q
Definition at line 234 of file statevector.cpp.
References apply_1q(), gate_y(), and num::BasicVector< T >::size().
expectation_z()
real num::quantum::expectation_z (const Statevector & sv, int qubit)
<Z_q> = P(q=0) - P(q=1) for qubit q
Definition at line 214 of file statevector.cpp.
References num::BasicVector< T >::size().
gate2q_cnot()
Gate2Q num::quantum::gate2q_cnot ()
CNOT (qubit 0 = control, qubit 1 = target in subspace)
Definition at line 88 of file statevector.cpp.
gate2q_cz()
Gate2Q num::quantum::gate2q_cz ()
Controlled-Z.
Definition at line 97 of file statevector.cpp.
gate2q_swap()
Gate2Q num::quantum::gate2q_swap ()
SWAP.
Definition at line 106 of file statevector.cpp.
gate_h()
Gate num::quantum::gate_h ()
Hadamard.
Definition at line 36 of file statevector.cpp.
gate_p()
Gate num::quantum::gate_p (real lambda)
Phase gate: diag(1, e^{ilambda})
Definition at line 70 of file statevector.cpp.
gate_rx()
Gate num::quantum::gate_rx (real theta)
Rotation about X: R_x(theta) = exp(-ithetaX/2)
Definition at line 57 of file statevector.cpp.
gate_ry()
Gate num::quantum::gate_ry (real theta)
Rotation about Y: R_y(theta) = exp(-ithetaY/2)
Definition at line 61 of file statevector.cpp.
gate_rz()
Gate num::quantum::gate_rz (real theta)
Rotation about Z: R_z(theta) = exp(-ithetaZ/2)
Definition at line 65 of file statevector.cpp.
gate_s()
Gate num::quantum::gate_s ()
Phase gate S = diag(1, i)
Definition at line 41 of file statevector.cpp.
gate_sdg()
Gate num::quantum::gate_sdg ()
Sdg = diag(1, -i)
Definition at line 44 of file statevector.cpp.
gate_t()
Gate num::quantum::gate_t ()
T gate = diag(1, e^{ipi/4})
Definition at line 48 of file statevector.cpp.
References num::pi.
gate_tdg()
Gate num::quantum::gate_tdg ()
Tdg gate.
Definition at line 52 of file statevector.cpp.
References num::pi.
gate_u()
Gate num::quantum::gate_u (real theta, real phi, real lambda)
General SU(2) gate.
Definition at line 77 of file statevector.cpp.
References num::phi.
gate_x()
Gate num::quantum::gate_x ()
Pauli-X (NOT)
Definition at line 26 of file statevector.cpp.
Referenced by expectation_x().
gate_y()
Gate num::quantum::gate_y ()
Pauli-Y.
Definition at line 29 of file statevector.cpp.
Referenced by expectation_y().
gate_z()
Gate num::quantum::gate_z ()
Pauli-Z.
Definition at line 32 of file statevector.cpp.
norm()
real num::quantum::norm (const Statevector & sv)
L2 norm of the statevector (should be 1 for a valid quantum state)
Definition at line 187 of file statevector.cpp.
References num::norm().
Referenced by main().
normalize()
void num::quantum::normalize (Statevector & sv)
Normalize statevector in-place.
Definition at line 191 of file statevector.cpp.
References num::norm().
probabilities()
std::vector< real > num::quantum::probabilities (const Statevector & sv)
Measurement probability for each basis state: p_i = |a_i|^2.
Definition at line 197 of file statevector.cpp.
References num::BasicVector< T >::size().
Referenced by main(), and num::Circuit::run().
reduced_density_matrix()
std::array< cplx, 4 > num::quantum::reduced_density_matrix (const Statevector & sv, int n_qubits, int qubit)
Reduced density matrix for a single qubit (2x2, returned row-major)
Definition at line 243 of file statevector.cpp.
Referenced by entanglement_entropy().
zero_state()
Statevector num::quantum::zero_state (int n_qubits)
Returns |0...0> computational basis state for n_qubits qubits.
Definition at line 12 of file statevector.cpp.
Referenced by num::Circuit::statevector_at().