numerics: num::backends::gpu Namespace Reference
num::backends::gpu Namespace Reference
Functions
void scale (Vector &v, real alpha)
void axpy (real alpha, const Vector &x, Vector &y)
real dot (const Vector &x, const Vector &y)
real norm (const Vector &x)
void matmul (const Matrix &A, const Matrix &B, Matrix &C)
void matvec (const Matrix &A, const Vector &x, Vector &y)
Function Documentation
axpy()
void num::backends::gpu::axpy (real alpha, const Vector & x, Vector & y)
Definition at line 22 of file vector.cpp.
References num::cuda::axpy(), num::backends::seq::axpy(), num::BasicVector< T >::gpu_data(), and num::BasicVector< T >::size().
Referenced by num::axpy().
dot()
real num::backends::gpu::dot (const Vector & x, const Vector & y)
Definition at line 30 of file vector.cpp.
References num::cuda::dot(), num::backends::seq::dot(), num::BasicVector< T >::gpu_data(), and num::BasicVector< T >::size().
Referenced by num::dot().
matmul()
void num::backends::gpu::matmul (const Matrix & A, const Matrix & B, Matrix & C)
Definition at line 13 of file matrix.cpp.
References num::Matrix::cols(), num::Matrix::gpu_data(), num::backends::seq::matmul(), num::cuda::matmul(), and num::Matrix::rows().
Referenced by num::matmul().
matvec()
void num::backends::gpu::matvec (const Matrix & A, const Vector & x, Vector & y)
Definition at line 26 of file matrix.cpp.
References num::Matrix::cols(), num::Matrix::gpu_data(), num::BasicVector< T >::gpu_data(), num::backends::seq::matvec(), num::cuda::matvec(), and num::Matrix::rows().
Referenced by num::matvec().
norm()
real num::backends::gpu::norm (const Vector & x)
Definition at line 38 of file vector.cpp.
References num::cuda::dot(), num::BasicVector< T >::gpu_data(), num::backends::seq::norm(), and num::BasicVector< T >::size().
Referenced by num::norm().
scale()
void num::backends::gpu::scale (Vector & v, real alpha)
Definition at line 14 of file vector.cpp.
References num::BasicVector< T >::gpu_data(), num::cuda::scale(), num::backends::seq::scale(), and num::BasicVector< T >::size().
Referenced by num::scale().