numerics: num::ode Namespace Reference
num::ode Namespace Reference
Classes
struct ImplicitParams
Parameters for fixed-step implicit integration.
Functions
template<VecField Field, typename Observer >
void advance (Field &u, const LinearSolver &solver, ImplicitParams p, Observer &&obs)
template<VecField Field>
void advance (Field &u, const LinearSolver &solver, ImplicitParams p)
Overload without observer.
Function Documentation
advance() [1/2]
template<VecField Field> void num::ode::advance (Field & u, const LinearSolver & solver, ImplicitParams p)
Overload without observer.
Definition at line 45 of file implicit.hpp.
References num::ode::ImplicitParams::nstep, and num::BasicVector< T >::vec().
advance() [2/2]
template<VecField Field, typename Observer > void num::ode::advance (Field & u, const LinearSolver & solver, ImplicitParams p, Observer && obs)
Advance u by nstep implicit steps using solver. obs(step, t, u) is called at step 0 (initial) and after each solve.
Definition at line 34 of file implicit.hpp.
References num::ode::ImplicitParams::dt, num::ode::ImplicitParams::nstep, and num::BasicVector< T >::vec().
Referenced by num::solve(), and num::solve().