numerics: nbody Namespace Reference
nbody Namespace Reference
Classes
struct Body
struct NBodySim
Enumerations
enum class Scenario { Figure8 , SolarSystem , BinaryPlus , Galaxy }
Functions
const char * scenario_name (Scenario s)
uint32_t mass_color (double m)
float disp_r (double m)
float phys_r (double m)
Enumeration Type Documentation
Scenario
enum class nbody::Scenario strong
Enumerator
Figure8
Chenciner-Montgomery figure-8 choreography (3 equal masses)
SolarSystem
Sun + 4 planets on circular Keplerian orbits.
BinaryPlus
Equal-mass binary + one test particle on a wide orbit.
Galaxy
Random N bodies – gravity only, bodies merge on contact.
Definition at line 43 of file sim.hpp.
Function Documentation
disp_r()
float nbody::disp_r (double m)
Definition at line 33 of file sim.cpp.
Referenced by nbody::NBodySim::check_merges(), and nbody::NBodySim::reset().
mass_color()
uint32_t nbody::mass_color (double m)
Definition at line 12 of file sim.cpp.
Referenced by nbody::NBodySim::check_merges(), and nbody::NBodySim::reset().
phys_r()
float nbody::phys_r (double m)
Definition at line 36 of file sim.cpp.
Referenced by nbody::NBodySim::check_merges(), and nbody::NBodySim::reset().
scenario_name()
const char * nbody::scenario_name (Scenario s) inline
Definition at line 50 of file sim.hpp.
References BinaryPlus, Figure8, Galaxy, and SolarSystem.