numerics: num::backends::simd Namespace Reference
num::backends::simd Namespace Reference
Functions
void matmul (const Matrix &A, const Matrix &B, Matrix &C, idx block_size)
void matvec (const Matrix &A, const Vector &x, Vector &y)
Function Documentation
matmul()
void num::backends::simd::matmul (const Matrix & A, const Matrix & B, Matrix & C, idx block_size)
Definition at line 248 of file matrix.cpp.
References num::backends::seq::matmul_blocked().
Referenced by num::matmul(), and num::matmul_simd().
matvec()
void num::backends::simd::matvec (const Matrix & A, const Vector & x, Vector & y)
Definition at line 258 of file matrix.cpp.
References num::backends::seq::matvec().
Referenced by num::matvec(), and num::matvec_simd().