numerics: physics::backends::seq Namespace Reference
physics::backends::seq Namespace Reference
Functions
void compute_density_pressure (std::vector< Particle > &particles, const FluidParams &params, const SpatialHash &grid)
Newton's 3rd law pair traversal – O(n*k/2).
void compute_forces (std::vector< Particle > &particles, const FluidParams &params, const SpatialHash &grid)
Newton's 3rd law pair traversal – O(n*k/2).
void body_collisions (std::vector< Particle > &particles, const std::vector< RigidBody > &bodies, const FluidParams &params)
void integrate (std::vector< Particle > &particles, const FluidParams &params)
void enforce_boundaries (std::vector< Particle > &particles, const FluidParams &params)
void update_temp_range (const std::vector< Particle > &particles, const std::vector< RigidBody > &bodies, float &T_min, float &T_max)
void integrate_bodies (std::vector< RigidBody > &bodies, const FluidParams &params)
void heat_compute (std::vector< Particle > &particles, const std::vector< RigidBody > &bodies, const SpatialHash &grid, const HeatParams &params)
void compute_density_pressure (std::vector< Particle3D > &particles, const FluidParams3D &params, const SpatialHash3D &grid)
void compute_forces (std::vector< Particle3D > &particles, const FluidParams3D &params, const SpatialHash3D &grid)
void body_collisions (std::vector< Particle3D > &particles, const std::vector< RigidBody3D > &bodies, const FluidParams3D &params)
void integrate (std::vector< Particle3D > &particles, const FluidParams3D &params)
void enforce_boundaries (std::vector< Particle3D > &particles, const FluidParams3D &params)
void update_temp_range (const std::vector< Particle3D > &particles, const std::vector< RigidBody3D > &bodies, float &T_min, float &T_max)
void integrate_bodies (std::vector< RigidBody3D > &bodies, const FluidParams3D &params)
void heat_compute (std::vector< Particle3D > &particles, const std::vector< RigidBody3D > &bodies, const SpatialHash3D &grid, const HeatParams3D &params)
Function Documentation
body_collisions() [1/2]
void physics::backends::seq::body_collisions (std::vector< Particle > & particles, const std::vector< RigidBody > & bodies, const FluidParams & params)
Definition at line 102 of file fluid.cpp.
References physics::FluidParams::restitution.
Referenced by physics::backends::omp::body_collisions(), physics::backends::omp::body_collisions(), physics::FluidSolver::step(), and physics::FluidSolver3D::step().
body_collisions() [2/2]
void physics::backends::seq::body_collisions (std::vector< Particle3D > & particles, const std::vector< RigidBody3D > & bodies, const FluidParams3D & params)
Definition at line 98 of file fluid.cpp.
References physics::FluidParams3D::restitution.
compute_density_pressure() [1/2]
void physics::backends::seq::compute_density_pressure (std::vector< Particle > & particles, const FluidParams & params, const SpatialHash & grid)
Newton's 3rd law pair traversal – O(n*k/2).
Definition at line 23 of file fluid.cpp.
References physics::FluidParams::c0, physics::FluidParams::gamma, physics::FluidParams::h, physics::SpatialHash::iterate_pairs(), physics::FluidParams::mass, physics::FluidParams::rho0, and num::SPHKernel< Dim >::W().
Referenced by physics::backends::omp::compute_density_pressure(), physics::backends::omp::compute_density_pressure(), physics::FluidSolver::step(), and physics::FluidSolver3D::step().
compute_density_pressure() [2/2]
void physics::backends::seq::compute_density_pressure (std::vector< Particle3D > & particles, const FluidParams3D & params, const SpatialHash3D & grid)
Definition at line 15 of file fluid.cpp.
References physics::FluidParams3D::c0, physics::FluidParams3D::gamma, physics::FluidParams3D::h, physics::SpatialHash3D::iterate_pairs(), physics::FluidParams3D::mass, physics::FluidParams3D::rho0, and num::SPHKernel< Dim >::W().
compute_forces() [1/2]
void physics::backends::seq::compute_forces (std::vector< Particle > & particles, const FluidParams & params, const SpatialHash & grid)
Newton's 3rd law pair traversal – O(n*k/2).
Definition at line 57 of file fluid.cpp.
References physics::Particle::ax, physics::Particle::ay, physics::Particle::density, physics::Particle::evx, physics::Particle::evy, physics::FluidParams::gx, physics::FluidParams::gy, physics::FluidParams::h, physics::SpatialHash::iterate_pairs(), physics::FluidParams::mass, physics::FluidParams::mu, num::pi, physics::Particle::pressure, num::SPHKernel< Dim >::Spiky_dW_dr(), num::SPHKernel< Dim >::Spiky_gradW(), physics::Particle::x, and physics::Particle::y.
Referenced by physics::backends::omp::compute_forces(), physics::backends::omp::compute_forces(), physics::FluidSolver::step(), and physics::FluidSolver3D::step().
compute_forces() [2/2]
void physics::backends::seq::compute_forces (std::vector< Particle3D > & particles, const FluidParams3D & params, const SpatialHash3D & grid)
Definition at line 48 of file fluid.cpp.
References physics::Particle3D::ax, physics::Particle3D::ay, physics::Particle3D::az, physics::Particle3D::density, physics::Particle3D::evx, physics::Particle3D::evy, physics::Particle3D::evz, physics::FluidParams3D::gx, physics::FluidParams3D::gy, physics::FluidParams3D::gz, physics::FluidParams3D::h, physics::SpatialHash3D::iterate_pairs(), physics::FluidParams3D::mass, physics::FluidParams3D::mu, physics::Particle3D::pressure, num::SPHKernel< Dim >::Spiky_dW_dr(), num::SPHKernel< Dim >::Spiky_gradW(), physics::Particle3D::x, physics::Particle3D::y, and physics::Particle3D::z.
enforce_boundaries() [1/2]
void physics::backends::seq::enforce_boundaries (std::vector< Particle > & particles, const FluidParams & params)
Definition at line 137 of file fluid.cpp.
References num::e, physics::FluidParams::restitution, physics::FluidParams::xmax, physics::FluidParams::xmin, physics::FluidParams::ymax, and physics::FluidParams::ymin.
Referenced by physics::backends::omp::enforce_boundaries(), physics::backends::omp::enforce_boundaries(), physics::FluidSolver::step(), and physics::FluidSolver3D::step().
enforce_boundaries() [2/2]
void physics::backends::seq::enforce_boundaries (std::vector< Particle3D > & particles, const FluidParams3D & params)
Definition at line 140 of file fluid.cpp.
References physics::FluidParams3D::restitution, physics::FluidParams3D::xmax, physics::FluidParams3D::xmin, physics::FluidParams3D::ymax, physics::FluidParams3D::ymin, physics::FluidParams3D::zmax, and physics::FluidParams3D::zmin.
heat_compute() [1/2]
void physics::backends::seq::heat_compute (std::vector< Particle > & particles, const std::vector< RigidBody > & bodies, const SpatialHash & grid, const HeatParams & params)
Definition at line 13 of file heat.cpp.
References physics::HeatParams::alpha_T, physics::Particle::density, num::SPHKernel< Dim >::dW_dr(), physics::HeatParams::h, physics::HeatParams::h_conv, physics::HeatParams::mass, physics::SpatialHash::query(), physics::Particle::temperature, physics::Particle::x, and physics::Particle::y.
Referenced by physics::backends::omp::heat_compute(), physics::backends::omp::heat_compute(), physics::FluidSolver::step(), and physics::FluidSolver3D::step().
heat_compute() [2/2]
void physics::backends::seq::heat_compute (std::vector< Particle3D > & particles, const std::vector< RigidBody3D > & bodies, const SpatialHash3D & grid, const HeatParams3D & params)
Definition at line 13 of file heat.cpp.
References physics::HeatParams3D::alpha_T, physics::Particle3D::density, num::SPHKernel< Dim >::dW_dr(), physics::HeatParams3D::h, physics::HeatParams3D::h_conv, physics::HeatParams3D::mass, physics::SpatialHash3D::query(), physics::Particle3D::temperature, physics::Particle3D::x, physics::Particle3D::y, and physics::Particle3D::z.
integrate() [1/2]
void physics::backends::seq::integrate (std::vector< Particle > & particles, const FluidParams & params)
Definition at line 123 of file fluid.cpp.
References physics::FluidParams::dt.
Referenced by physics::backends::omp::integrate(), physics::backends::omp::integrate(), physics::FluidSolver::step(), and physics::FluidSolver3D::step().
integrate() [2/2]
void physics::backends::seq::integrate (std::vector< Particle3D > & particles, const FluidParams3D & params)
Definition at line 122 of file fluid.cpp.
References physics::FluidParams3D::dt.
integrate_bodies() [1/2]
void physics::backends::seq::integrate_bodies (std::vector< RigidBody > & bodies, const FluidParams & params)
Definition at line 177 of file fluid.cpp.
References physics::FluidParams::dt, num::e, physics::FluidParams::gx, physics::FluidParams::gy, physics::FluidParams::restitution, physics::FluidParams::xmax, physics::FluidParams::xmin, physics::FluidParams::ymax, and physics::FluidParams::ymin.
Referenced by physics::FluidSolver::step(), and physics::FluidSolver3D::step().
integrate_bodies() [2/2]
void physics::backends::seq::integrate_bodies (std::vector< RigidBody3D > & bodies, const FluidParams3D & params)
Definition at line 188 of file fluid.cpp.
References physics::FluidParams3D::dt, physics::FluidParams3D::gx, physics::FluidParams3D::gy, physics::FluidParams3D::gz, physics::FluidParams3D::restitution, physics::FluidParams3D::xmax, physics::FluidParams3D::xmin, physics::FluidParams3D::ymax, physics::FluidParams3D::ymin, physics::FluidParams3D::zmax, and physics::FluidParams3D::zmin.
update_temp_range() [1/2]
void physics::backends::seq::update_temp_range (const std::vector< Particle > & particles, const std::vector< RigidBody > & bodies, float & T_min, float & T_max)
Definition at line 160 of file fluid.cpp.
Referenced by physics::FluidSolver::step(), physics::FluidSolver3D::step(), physics::backends::omp::update_temp_range(), and physics::backends::omp::update_temp_range().
update_temp_range() [2/2]
void physics::backends::seq::update_temp_range (const std::vector< Particle3D > & particles, const std::vector< RigidBody3D > & bodies, float & T_min, float & T_max)
Definition at line 171 of file fluid.cpp.