numerics: num::backends::blas Namespace Reference
num::backends::blas Namespace Reference
Functions
void scale (Vector &v, real alpha)
void axpy (real alpha, const Vector &x, Vector &y)
real dot (const Vector &x, const Vector &y)
real norm (const Vector &x)
void matmul (const Matrix &A, const Matrix &B, Matrix &C)
void matvec (const Matrix &A, const Vector &x, Vector &y)
void matadd (real alpha, const Matrix &A, real beta, const Matrix &B, Matrix &C)
Function Documentation
axpy()
void num::backends::blas::axpy (real alpha, const Vector & x, Vector & y)
Definition at line 42 of file vector.cpp.
References num::backends::seq::axpy(), num::BasicVector< T >::data(), and num::BasicVector< T >::size().
Referenced by num::axpy().
dot()
real num::backends::blas::dot (const Vector & x, const Vector & y)
Definition at line 51 of file vector.cpp.
References num::BasicVector< T >::data(), num::backends::seq::dot(), and num::BasicVector< T >::size().
Referenced by num::dot().
matadd()
void num::backends::blas::matadd (real alpha, const Matrix & A, real beta, const Matrix & B, Matrix & C)
Definition at line 79 of file matrix.cpp.
References num::beta(), num::Matrix::data(), num::backends::seq::matadd(), and num::Matrix::size().
Referenced by num::matadd().
matmul()
void num::backends::blas::matmul (const Matrix & A, const Matrix & B, Matrix & C)
Definition at line 37 of file matrix.cpp.
References num::Matrix::cols(), num::Matrix::data(), num::backends::seq::matmul_blocked(), and num::Matrix::rows().
Referenced by num::matmul().
matvec()
void num::backends::blas::matvec (const Matrix & A, const Vector & x, Vector & y)
Definition at line 59 of file matrix.cpp.
References num::Matrix::cols(), num::Matrix::data(), num::BasicVector< T >::data(), num::backends::seq::matvec(), and num::Matrix::rows().
Referenced by num::matvec().
norm()
real num::backends::blas::norm (const Vector & x)
Definition at line 60 of file vector.cpp.
References num::BasicVector< T >::data(), num::backends::seq::norm(), and num::BasicVector< T >::size().
Referenced by num::norm().
scale()
void num::backends::blas::scale (Vector & v, real alpha)
Definition at line 33 of file vector.cpp.
References num::BasicVector< T >::data(), num::backends::seq::scale(), and num::BasicVector< T >::size().
Referenced by num::scale().