numerics: /home/runner/work/numerics/numerics/apps/nbody/main.cpp File Reference
main.cpp File Reference
Gravitational N-body simulation – galaxy collapse.
#include "numerics.hpp"
#include "viz/viz.hpp"
#include "nbody/sim.hpp"
#include <deque>
#include <vector>
Classes
struct V2
Typedefs
using real = double
Functions
template<class To , class From >
constexpr To cast (From x)
template<class T >
constexpr auto move (T &&x)
int main ()
Detailed Description
Gravitational N-body simulation – galaxy collapse.
N=200 bodies, symplectic Verlet integrator, trail rendering. SPACE pause R reset +/- substeps
Definition in file main.cpp.
Typedef Documentation
real
using real = double
Definition at line 17 of file main.cpp.
Function Documentation
cast()
template<class To , class From > constexpr To cast (From x) constexpr
Definition at line 19 of file main.cpp.
main()
int main ()
Definition at line 41 of file main.cpp.
References nbody::NBodySim::enable_merges, nbody::Galaxy, nbody::NBodySim::n(), nbody::NBodySim::q, nbody::NBodySim::reset(), num::viz::Frame::reset_pressed(), num::viz::run(), nbody::NBodySim::step(), and num::viz::Frame::step().
move()
template<class T > constexpr auto move (T && x) constexpr
Definition at line 23 of file main.cpp.