numerics: Hose Struct Reference
Hose Struct Reference
Public Member Functions
void init (Vector3 src, Vector3 target, float temp, float spd, float half_angle)
void emit (physics::FluidSolver3D &solver, int count, int max_n=1800) const
Static Public Member Functions
static Vector3 norm (Vector3 v)
static Vector3 cross (Vector3 a, Vector3 b)
Public Attributes
Vector3 source
Vector3 dir
Vector3 perp_u
Vector3 perp_v
float temperature
float speed
float cone_half
Detailed Description
Definition at line 45 of file main.cpp.
Member Function Documentation
cross()
static Vector3 Hose::cross (Vector3 a, Vector3 b) inline static
Definition at line 54 of file main.cpp.
Referenced by init().
emit()
void Hose::emit (physics::FluidSolver3D & solver, int count, int max_n = 1800) const inline
Definition at line 75 of file main.cpp.
References physics::FluidSolver3D::add_particle(), cone_half, dir, norm(), physics::FluidSolver3D::particles(), perp_u, perp_v, source, speed, and temperature.
init()
void Hose::init (Vector3 src, Vector3 target, float temp, float spd, float half_angle) inline
Definition at line 60 of file main.cpp.
References cone_half, cross(), dir, norm(), perp_u, perp_v, source, speed, and temperature.
Referenced by main().
norm()
static Vector3 Hose::norm (Vector3 v) inline static
Definition at line 49 of file main.cpp.
Referenced by emit(), and init().
Member Data Documentation
cone_half
float Hose::cone_half
Definition at line 47 of file main.cpp.
Referenced by emit(), and init().
dir
Vector3 Hose::dir
Definition at line 46 of file main.cpp.
Referenced by emit(), and init().
perp_u
Vector3 Hose::perp_u
Definition at line 46 of file main.cpp.
Referenced by emit(), and init().
perp_v
Vector3 Hose::perp_v
Definition at line 46 of file main.cpp.
Referenced by emit(), and init().
source
Vector3 Hose::source
Definition at line 46 of file main.cpp.
Referenced by emit(), init(), and main().
speed
float Hose::speed
Definition at line 47 of file main.cpp.
Referenced by emit(), and init().
temperature
float Hose::temperature
Definition at line 47 of file main.cpp.
Referenced by emit(), and init().
The documentation for this struct was generated from the following file:
/home/runner/work/numerics/numerics/apps/fluid_sim_3d/main.cpp