numerics: num::kernel::subspace::DenseOp Struct Reference
num::kernel::subspace::DenseOp Struct Reference final
Wrap a dense Matrix as a LinearOp.
#include <subspace.hpp>
Public Member Functions
DenseOp (const Matrix &A, Backend b=default_backend)
void apply (const Vector &x, Vector &y) const override
y = A*x (y must be pre-allocated to the correct size)
idx rows () const noexcept override
idx cols () const noexcept override
Public Member Functions inherited from num::kernel::subspace::LinearOp
virtual ~LinearOp ()=default
Detailed Description
Wrap a dense Matrix as a LinearOp.
The matvec is dispatched to the chosen Backend (default: default_backend).
Definition at line 68 of file subspace.hpp.
Constructor & Destructor Documentation
DenseOp()
num::kernel::subspace::DenseOp::DenseOp (const Matrix & A, Backend b = default_backend) inline explicit
Definition at line 69 of file subspace.hpp.
Member Function Documentation
apply()
void num::kernel::subspace::DenseOp::apply (const Vector & x, Vector & y) const override virtual
y = A*x (y must be pre-allocated to the correct size)
Implements num::kernel::subspace::LinearOp.
Definition at line 18 of file subspace.cpp.
References num::matvec(), num::Matrix::rows(), and num::BasicVector< T >::size().
cols()
idx num::kernel::subspace::DenseOp::cols () const inline override virtual noexcept
Implements num::kernel::subspace::LinearOp.
Definition at line 74 of file subspace.hpp.
rows()
idx num::kernel::subspace::DenseOp::rows () const inline override virtual noexcept
Implements num::kernel::subspace::LinearOp.
Definition at line 73 of file subspace.hpp.
The documentation for this struct was generated from the following files:
/home/runner/work/numerics/numerics/include/kernel/subspace.hpp
/home/runner/work/numerics/numerics/src/kernel/subspace.cpp