numerics: nbody::NBodySim Struct Reference
nbody::NBodySim Struct Reference
#include <sim.hpp>
Public Types
enum class Integrator { Verlet , Yoshida4 , RK4 }
Public Member Functions
void reset (Scenario s)
Reset to a preset scenario.
void step (double dt)
Advance by exactly one time step dt.
std::vector< std::pair< int, int > > check_merges ()
int n () const
double kinetic_energy () const
double potential_energy () const
double total_energy () const
double energy_drift () const
Relative energy drift since reset: (E - E0) / |E0|.
void make_accel (const Vector &pos, Vector &acc) const
Public Attributes
std::vector< Body > bodies
Vector q
Positions: [x0,y0, x1,y1, ...].
Vector v
Velocities: [vx0,vy0, vx1,vy1, ...].
double t = 0.0
double G = 1.0
double E0 = 0.0
Initial total energy (for drift tracking)
double soft = 1e-3
Softening length (avoids singularities)
Integrator integrator = Integrator::Verlet
bool enable_merges
true = check_merges() is active (Galaxy scenario)
Detailed Description
Definition at line 74 of file sim.hpp.
Member Enumeration Documentation
Integrator
enum class nbody::NBodySim::Integrator strong
Enumerator
Verlet
Yoshida4
RK4
Definition at line 83 of file sim.hpp.
Member Function Documentation
check_merges()
std::vector< std::pair< int, int > > nbody::NBodySim::check_merges ()
Check all pairs for contact; merge overlapping bodies. Returns the list of (removed_idx, swapped_from_idx) operations in order so the caller can mirror them on any parallel index array (e.g. trails).
Definition at line 104 of file sim.cpp.
References bodies, nbody::disp_r(), nbody::mass_color(), n(), nbody::phys_r(), q, v, and num::Vec2View::x().
energy_drift()
double nbody::NBodySim::energy_drift () const inline
Relative energy drift since reset: (E - E0) / |E0|.
Definition at line 110 of file sim.hpp.
References E0, and total_energy().
kinetic_energy()
double nbody::NBodySim::kinetic_energy () const
Definition at line 59 of file sim.cpp.
References bodies, n(), and v.
Referenced by total_energy().
make_accel()
void nbody::NBodySim::make_accel (const Vector & pos, Vector & acc) const
Fill acc from current positions (gravitational acceleration on each body).
Definition at line 40 of file sim.cpp.
References num::BasicVector< T >::begin(), bodies, num::BasicVector< T >::end(), G, n(), and soft.
Referenced by step().
n()
int nbody::NBodySim::n () const inline
Definition at line 99 of file sim.hpp.
References bodies.
Referenced by check_merges(), kinetic_energy(), main(), make_accel(), and potential_energy().
potential_energy()
double nbody::NBodySim::potential_energy () const
Definition at line 68 of file sim.cpp.
References bodies, G, n(), q, soft, and num::Vec2ConstView::x().
Referenced by total_energy().
reset()
void nbody::NBodySim::reset (Scenario s)
Reset to a preset scenario.
Definition at line 159 of file sim.cpp.
References nbody::BinaryPlus, bodies, nbody::disp_r(), E0, enable_merges, nbody::Figure8, G, nbody::mass_color(), nbody::phys_r(), q, soft, nbody::SolarSystem, t, total_energy(), v, and num::Vec2View::x().
Referenced by main().
step()
void nbody::NBodySim::step (double dt)
Advance by exactly one time step dt.
Definition at line 82 of file sim.cpp.
References integrator, make_accel(), q, num::SymplecticResult::q, RK4, num::rk4_2nd(), num::VerletSteps::run(), num::Yoshida4Steps::run(), num::RK4_2ndSteps::run(), t, num::ODEParams::t0, v, num::SymplecticResult::v, Verlet, num::verlet(), Yoshida4, and num::yoshida4().
Referenced by main().
total_energy()
double nbody::NBodySim::total_energy () const inline
Definition at line 105 of file sim.hpp.
References kinetic_energy(), and potential_energy().
Referenced by energy_drift(), and reset().
Member Data Documentation
bodies
std::vector<Body> nbody::NBodySim::bodies
Definition at line 75 of file sim.hpp.
Referenced by check_merges(), kinetic_energy(), make_accel(), n(), potential_energy(), and reset().
E0
double nbody::NBodySim::E0 = 0.0
Initial total energy (for drift tracking)
Definition at line 80 of file sim.hpp.
Referenced by energy_drift(), and reset().
enable_merges
bool nbody::NBodySim::enable_merges
Initial value:
=
        false
true = check_merges() is active (Galaxy scenario)
Definition at line 85 of file sim.hpp.
Referenced by main(), and reset().
G
double nbody::NBodySim::G = 1.0
Definition at line 79 of file sim.hpp.
Referenced by make_accel(), potential_energy(), and reset().
integrator
Integrator nbody::NBodySim::integrator = Integrator::Verlet
Definition at line 84 of file sim.hpp.
Referenced by step().
q
Vector nbody::NBodySim::q
Positions: [x0,y0, x1,y1, ...].
Definition at line 76 of file sim.hpp.
Referenced by check_merges(), main(), potential_energy(), reset(), and step().
soft
double nbody::NBodySim::soft = 1e-3
Softening length (avoids singularities)
Definition at line 81 of file sim.hpp.
Referenced by make_accel(), potential_energy(), and reset().
t
double nbody::NBodySim::t = 0.0
Definition at line 78 of file sim.hpp.
Referenced by reset(), and step().
v
Vector nbody::NBodySim::v
Velocities: [vx0,vy0, vx1,vy1, ...].
Definition at line 77 of file sim.hpp.
Referenced by check_merges(), kinetic_energy(), reset(), and step().
The documentation for this struct was generated from the following files:
/home/runner/work/numerics/numerics/apps/nbody/include/nbody/sim.hpp
/home/runner/work/numerics/numerics/apps/nbody/src/sim.cpp