numerics: IsingLattice< N > Struct Template Reference
IsingLattice< N > Struct Template Reference
#include <sim.hpp>
Public Member Functions
IsingLattice ()
void set_temperature (real T)
void set_field (real Fnew)
real temperature () const
void random_init ()
void all_up ()
void generate_nucleus (real r=100.0)
void sweep ()
int sweep_umbrella (int lo, int hi, num::ClusterResult &det)
real magnetization () const
|<m>| = |sum(s_i)| / N^2 via SIMD dot product.
real energy_per_spin ()
<E>/N^2 using the sparse adjacency matrix and SIMD sparse_matvec.
Static Public Member Functions
static real mean_field_m (real beta_val, real F_val)
Public Attributes
num::Vector spins
NN spins: values +/-1.
real beta
Inverse temperature.
real F
External field.
Static Public Attributes
static constexpr int NN = N * N
static constexpr real J = 1.0
static const real TC = 2.26918531421
Onsager exact critical temperature.
Detailed Description
template<int N>
struct IsingLattice< N >
Definition at line 35 of file sim.hpp.
Constructor & Destructor Documentation
IsingLattice()
template<int N> IsingLattice< N >::IsingLattice () inline
Definition at line 44 of file sim.hpp.
References IsingLattice< N >::random_init().
Member Function Documentation
all_up()
template<int N> void IsingLattice< N >::all_up () inline
Definition at line 81 of file sim.hpp.
References IsingLattice< N >::NN, and IsingLattice< N >::spins.
Referenced by IsingLattice< N >::generate_nucleus().
energy_per_spin()
template<int N> real IsingLattice< N >::energy_per_spin () inline
<E>/N^2 using the sparse adjacency matrix and SIMD sparse_matvec.
Definition at line 161 of file sim.hpp.
References IsingLattice< N >::F, IsingLattice< N >::J, IsingLattice< N >::NN, num::seq, num::sparse_matvec(), and IsingLattice< N >::spins.
generate_nucleus()
template<int N> void IsingLattice< N >::generate_nucleus (real r = 100.0) inline
Square spin-down nucleus of area ~r centred at the middle of the lattice.
Definition at line 88 of file sim.hpp.
References IsingLattice< N >::all_up(), and IsingLattice< N >::spins.
magnetization()
template<int N> real IsingLattice< N >::magnetization () const inline
|<m>| = |sum(s_i)| / N^2 via SIMD dot product.
Definition at line 155 of file sim.hpp.
References IsingLattice< N >::NN, num::seq, and IsingLattice< N >::spins.
Referenced by main().
mean_field_m()
template<int N> static real IsingLattice< N >::mean_field_m (real beta_val, real F_val) inline static
Mean-field order parameter: solve m = tanh(4*beta*J*m + beta*F) via num::newton().
Definition at line 171 of file sim.hpp.
References IsingLattice< N >::J, and num::newton().
random_init()
template<int N> void IsingLattice< N >::random_init () inline
Definition at line 76 of file sim.hpp.
References IsingLattice< N >::NN, and IsingLattice< N >::spins.
Referenced by IsingLattice< N >::IsingLattice().
set_field()
template<int N> void IsingLattice< N >::set_field (real Fnew) inline
Definition at line 66 of file sim.hpp.
References IsingLattice< N >::F.
set_temperature()
template<int N> void IsingLattice< N >::set_temperature (real T) inline
Definition at line 62 of file sim.hpp.
References IsingLattice< N >::beta.
sweep()
template<int N> void IsingLattice< N >::sweep () inline
Standard Metropolis sweep: N^2 random spin picks with replacement. Uses a precomputed Boltzmann table – no exp() at runtime.
Definition at line 101 of file sim.hpp.
References num::PBCLattice2D::dn, num::PBCLattice2D::lt, num::markov::metropolis_sweep_prob(), IsingLattice< N >::NN, num::PBCLattice2D::rt, IsingLattice< N >::spins, and num::PBCLattice2D::up.
sweep_umbrella()
template<int N> int IsingLattice< N >::sweep_umbrella (int lo, int hi, num::ClusterResult & det) inline
Umbrella sweep: revert if nucleus size leaves [lo, hi]. Fills det with the connected-component result for rendering.
Definition at line 116 of file sim.hpp.
References num::connected_components(), num::PBCLattice2D::dn, num::ClusterResult::largest_size, num::PBCLattice2D::lt, IsingLattice< N >::NN, num::PBCLattice2D::rt, IsingLattice< N >::spins, num::markov::umbrella_sweep_prob(), and num::PBCLattice2D::up.
temperature()
template<int N> real IsingLattice< N >::temperature () const inline
Definition at line 70 of file sim.hpp.
References IsingLattice< N >::beta.
Member Data Documentation
beta
template<int N> real IsingLattice< N >::beta
Inverse temperature.
Definition at line 41 of file sim.hpp.
Referenced by IsingLattice< N >::set_temperature(), and IsingLattice< N >::temperature().
F
template<int N> real IsingLattice< N >::F
External field.
Definition at line 42 of file sim.hpp.
Referenced by IsingLattice< N >::energy_per_spin(), and IsingLattice< N >::set_field().
J
template<int N> constexpr real IsingLattice< N >::J = 1.0 static constexpr
Definition at line 37 of file sim.hpp.
Referenced by IsingLattice< N >::energy_per_spin(), and IsingLattice< N >::mean_field_m().
NN
template<int N> constexpr int IsingLattice< N >::NN = N * N static constexpr
Definition at line 36 of file sim.hpp.
Referenced by IsingLattice< N >::all_up(), IsingLattice< N >::energy_per_spin(), IsingLattice< N >::magnetization(), IsingLattice< N >::random_init(), IsingLattice< N >::sweep(), and IsingLattice< N >::sweep_umbrella().
spins
template<int N> num::Vector IsingLattice< N >::spins
NN spins: values +/-1.
Definition at line 40 of file sim.hpp.
Referenced by IsingLattice< N >::all_up(), IsingLattice< N >::energy_per_spin(), IsingLattice< N >::generate_nucleus(), IsingLattice< N >::magnetization(), main(), IsingLattice< N >::random_init(), IsingLattice< N >::sweep(), and IsingLattice< N >::sweep_umbrella().
TC
template<int N> const real IsingLattice< N >::TC = 2.26918531421 static
Onsager exact critical temperature.
Definition at line 38 of file sim.hpp.
The documentation for this struct was generated from the following file:
/home/runner/work/numerics/numerics/apps/ising/include/ising/sim.hpp