numerics: backends::opt::FFTPlanImpl Struct Reference
backends::opt::FFTPlanImpl Struct Reference
Precomputed twiddle factors + SIMD butterfly execution.
#include <impl.hpp>
Public Member Functions
FFTPlanImpl (int n_, bool inv)
void execute (num::CVector &a) const
Public Attributes
int n
bool invert
std::vector< std::vector< num::cplx > > twiddles
Detailed Description
Precomputed twiddle factors + SIMD butterfly execution.
Definition at line 140 of file impl.hpp.
Constructor & Destructor Documentation
FFTPlanImpl()
backends::opt::FFTPlanImpl::FFTPlanImpl (int n_, bool inv) inline
Definition at line 145 of file impl.hpp.
References twiddles.
Member Function Documentation
execute()
void backends::opt::FFTPlanImpl::execute (num::CVector & a) const inline
Definition at line 164 of file impl.hpp.
References backends::seq::bit_reverse(), num::BasicVector< T >::data(), n, and twiddles.
Referenced by backends::opt::fft(), backends::opt::ifft(), backends::opt::irfft(), and backends::opt::rfft().
Member Data Documentation
invert
bool backends::opt::FFTPlanImpl::invert
Definition at line 142 of file impl.hpp.
n
int backends::opt::FFTPlanImpl::n
Definition at line 141 of file impl.hpp.
Referenced by execute().
twiddles
std::vector<std::vector<num::cplx> > backends::opt::FFTPlanImpl::twiddles
Definition at line 143 of file impl.hpp.
Referenced by execute(), and FFTPlanImpl().
The documentation for this struct was generated from the following file:
/home/runner/work/numerics/numerics/src/spectral/backends/opt/impl.hpp