numerics: num::kernel::subspace::SparseOp Struct Reference
num::kernel::subspace::SparseOp Struct Reference final
Wrap a SparseMatrix as a LinearOp.
#include <subspace.hpp>
Public Member Functions
SparseOp (const SparseMatrix &A)
void apply (const Vector &x, Vector &y) const override
y = A*x (y must be pre-allocated to the correct size)
idx rows () const noexcept override
idx cols () const noexcept override
Public Member Functions inherited from num::kernel::subspace::LinearOp
virtual ~LinearOp ()=default
Detailed Description
Wrap a SparseMatrix as a LinearOp.
Definition at line 82 of file subspace.hpp.
Constructor & Destructor Documentation
SparseOp()
num::kernel::subspace::SparseOp::SparseOp (const SparseMatrix & A) inline explicit
Definition at line 83 of file subspace.hpp.
Member Function Documentation
apply()
void num::kernel::subspace::SparseOp::apply (const Vector & x, Vector & y) const override virtual
y = A*x (y must be pre-allocated to the correct size)
Implements num::kernel::subspace::LinearOp.
Definition at line 23 of file subspace.cpp.
References num::SparseMatrix::n_rows(), num::BasicVector< T >::size(), and num::sparse_matvec().
cols()
idx num::kernel::subspace::SparseOp::cols () const inline override virtual noexcept
Implements num::kernel::subspace::LinearOp.
Definition at line 87 of file subspace.hpp.
rows()
idx num::kernel::subspace::SparseOp::rows () const inline override virtual noexcept
Implements num::kernel::subspace::LinearOp.
Definition at line 86 of file subspace.hpp.
The documentation for this struct was generated from the following files:
/home/runner/work/numerics/numerics/include/kernel/subspace.hpp
/home/runner/work/numerics/numerics/src/kernel/subspace.cpp